import {StyleSheet,Dimensions} from 'react-native';
export const styles = StyleSheet.create({
  main:{
    flex:1,
    backgroundColor:'#f7f8fa',
  },
  imgBg:{
    width:Dimensions.get('window').width,
  },
  nav:{
    flexDirection:"row",
    height:64,
    paddingTop:20,
    justifyContent:"center",
    alignItems:'center',
  },
  navTitle:{
    height:44,
    flex:1,
    justifyContent:"center",
    alignItems:'center',
    backgroundColor:'transparent',
    width:Dimensions.get('window').width-160,
  },
  backIcon:{
    width:80,
    height:44,
    justifyContent:"center",
    alignItems:'flex-start',
    paddingLeft:15,
  },
  navLeft:{
    width:85,
    height:44,
    justifyContent:"center",
    alignItems:'flex-end',
    paddingRight:15,
  },
  view:{
    height:64,
    paddingTop:20,
    backgroundColor:'transparent',
    marginLeft:15,
    marginRight:15,
  },
  icon:{
    marginTop:15,
  },
  btn:{
    paddingLeft:5,
    paddingRight:5,
    borderWidth:1,
    borderColor:'rgba(255,255,255,0.7)',
    height:34,
    borderRadius:4,
    justifyContent:"center",
    alignItems:'center',
  },
  textAlignCenter:{
    textAlign:'center',
  },
  textAlignRight:{
    textAlign:'right',
  },
  row:{
    flexDirection:"row",
  },
  flex:{
    flex:1,
  },
  text:{
    marginTop:50,
    backgroundColor:'transparent',
    marginLeft:15,
    marginRight:15,
  },
  listBtn:{
    height:50,
    backgroundColor:'#fff',
    borderBottomWidth:1,
    borderBottomColor:'#eaeaea',
    paddingLeft:15,
    paddingRight:15,
    justifyContent:"center",
    alignItems:'center',
  },
  marginTop15:{
    marginTop:15,
  },
});
