import {StyleSheet,Dimensions} from 'react-native';
export const styles = StyleSheet.create({
  container:{
    flex:1,
    backgroundColor:'#f7f8fa',
  },
  main:{
    flex:1,
    backgroundColor:'#fff',
  },
  viewList:{
    flexDirection:"row",
    borderBottomWidth:1,
    borderColor:"#eaeaea",
    paddingLeft:15,
    paddingRight:15,
    height:50,
    backgroundColor:'#fff',
    alignItems:"center",
    justifyContent:"center",
  },
  date:{
    flex:1,
    textAlign:'right',
    marginRight:5,
  },
  icon:{
    marginTop:4,
  },
  row:{
    flexDirection:"row",
  },
  flex1:{
    flex:1,
  },
  tabView:{
    alignItems:"center",
    backgroundColor:"#f9f9f9",
    width:Dimensions.get('window').width,
    borderColor:"#eaeaea",
    borderBottomWidth:1,
    position:"relative"
  },
  tabsContainerStyle:{
    backgroundColor:"#f9f9f9",
    height:60,
    width:200,
    paddingTop:20
  },
  tabStyle:{
    borderWidth:0,
    borderRadius:0,
    backgroundColor:"#f9f9f9",
  },
  activeTabStyle:{
    backgroundColor:"#f9f9f9",
    borderBottomWidth:2,
    borderColor:"#3a8ff3",
    borderRadius:0,
  },
  activeTabTextStyle:{
    color:"#3a8ff3"
  },
  backView:{
    width:60,
    height:60,
    alignItems:"center",
    justifyContent:"center",
    position:"absolute",
    left:0,
    top:0,
    zIndex:10,
    paddingTop:15,
  },
  noCustomView:{
    marginTop:55,
    paddingLeft:80,
    paddingRight:80,
    alignItems:"center",
  },
  noCustom:{
    marginBottom:15,
  },
});
