import {StyleSheet,Dimensions} from 'react-native';
export const styles = StyleSheet.create({
  main:{
    flex:1,
    backgroundColor:'#fff',
  },
  webView:{
    width:Dimensions.get('window').width-30,
    flex:1,
    marginLeft:15,
    marginRight:15,
  },
  title:{
    height:36,
    lineHeight:36,
    textAlign:'center'
  },
  view:{
    marginLeft:15,
    marginRight:15,
  },
  viewRest:{
    marginLeft:15,
    marginRight:15,
    marginTop:20,
  },
  text:{
    lineHeight:22,
  },
  textView:{
    marginLeft:15,
    marginRight:15,
    marginTop:100,
  },
  listBtn:{
    width:Dimensions.get('window').width-30,
    marginLeft:15,
    marginRight:15,
    justifyContent:"center",
    alignItems:'center',
    borderRadius: 6,
    height:40,
    backgroundColor:'#3a8ff3',
    marginBottom:20,
  },
  listBtnGray:{
    width:Dimensions.get('window').width-30,
    marginLeft:15,
    marginRight:15,
    justifyContent:"center",
    alignItems:'center',
    borderRadius: 6,
    height:40,
    backgroundColor:'#ececec',
    marginBottom:20,
  },
  row:{
    flexDirection:"row",
    marginTop:5,
    height:30,
    alignItems:"center",
  },
  flex:{
    flex:1,
  },
  borderBottom:{
    borderBottomWidth:1,
    borderBottomColor:'rgba(58,143,243,0.7)',
    flex:1,
    height:30,
  },
  flexInput:{
    alignItems:"center",
    padding:0,
    margin:0,
    flex:1,
  },
  marginTop10:{
    marginTop:20,
  },
  marginTop100:{
    marginTop:100,
  },
  marginLeft15:{
    marginLeft:15,
  },
  marginRight15:{
    marginRight:15,
  },
  listText:{
    marginLeft:15,
    marginRight:15,
    marginTop:15,
  },
  listTextRow:{
    flexDirection:"row",
    alignItems:"center",
  },
  checkBoxView:{
    marginRight:10,
  }
});
