import {StyleSheet,Dimensions} from 'react-native';
export const styles = StyleSheet.create({
  mian:{
    flex:1,
    backgroundColor:"#f7f8fa",
  },
  list:{
    flexDirection:"row",
    borderBottomWidth:1,
    borderColor:"#eaeaea",
    paddingLeft:15,
    paddingRight:15,
    backgroundColor:'#fff',
    paddingTop:10,
    paddingBottom:10,
  },
  txt:{
    alignItems:"flex-start",
    justifyContent:"center",
    lineHeight:24,
  },
  remark:{
    flexDirection:"row",
    marginTop:10,
    borderBottomWidth:1,
    borderTopWidth:1,
    borderColor:"#eaeaea",
    paddingLeft:15,
    paddingRight:15,
    paddingTop:10,
    paddingBottom:10,
    backgroundColor:'#fff',
  },
  remark1:{
    flexDirection:"row",
    borderBottomWidth:1,
    borderColor:"#eaeaea",
    paddingLeft:15,
    paddingRight:15,
    paddingTop:10,
    paddingBottom:70,
    backgroundColor:'#fff',
  },
  lineHeight24:{
    lineHeight:24,
  },
  flex1:{
    flex:1,
  },
  offlineRight:{
    flex:1,
    paddingLeft:15,
    position:"relative",
    paddingRight:15
  },
  rightBottom:{
    flexDirection:"row",
    alignItems:"center"
  },

  tabView:{
    alignItems:"center",
    backgroundColor:"#f9f9f9",
    width:Dimensions.get('window').width,
    borderColor:"#eaeaea",
    borderBottomWidth:1,
    position:"relative"
  },
  activeTabTextStyle:{
    color:"#3a8ff3"
  },
  backView:{
    width:60,
    height:60,
    alignItems:"center",
    justifyContent:"center",
    position:"absolute",
    left:0,
    top:0,
    zIndex:10,
    paddingTop:15,
  },
  bottomTxt:{
    paddingBottom:5,
  },
  bottomBtn:{
    width:60,
    height:25,
    alignItems:"center",
    justifyContent:"center",
    borderColor:"#3a8ff3",
    borderWidth:1,
    borderRadius:3
  },
  bottomBtnText:{
    color:"#3a8ff3"
  },
  bottomTitle:{
    flex:1
  },
  EditView:{
    width:60,
    height:60,
    alignItems:"center",
    justifyContent:"center",
    position:"absolute",
    right:0,
    top:0,
    zIndex:10,
    paddingTop:15,
  },
  ForumListTitle:{
    flexDirection:"row",
    paddingLeft:15,
    paddingRight:15,
    alignItems:"center",
    borderBottomWidth:1,
    borderColor:"#ececec"
  },
  allianceText:{
    flex:1,
    paddingTop:8,
    paddingBottom:8,
  },
  proImg:{
    position:"absolute",
    left:15,
    right:0,
  },
  ForumText:{
    marginTop:10,
    flex:1,
  },
  bottomTop:{
    paddingBottom:12,
    marginTop:30,
  },
  flexView:{
    flex:3.5,
    flexDirection:"row",
  },
  flexTitle:{
    marginRight:20,
  },
  offlineRightRest:{
    borderColor:"#eaeaea",
    borderBottomWidth:1,
  },
  proImgRest:{
    position:"absolute",
    left:15,
    top:10,
  },








});
