import {
  StyleSheet,Dimensions
} from 'react-native';
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor:"#fff",
  },
  memberView:{
    backgroundColor:"#fff",
    borderBottomWidth:1,
    borderColor:"#f7f8fa",
  },
  memberTop:{
    flexDirection:"row",
    paddingLeft:15,
    paddingRight:15,
    paddingTop:17,
  },
  memberLeft:{
    alignItems:"center",
    justifyContent:"center",
    marginRight:5,
    width:25,
  },
  memberRight:{
    marginLeft:23,
    flex:1,
  },
  memberTitle:{
    marginBottom:12,
  },
  memberText:{
    flex:1,
    marginBottom:10,
  },
  rightBottom:{
    flexDirection:"row",
  },
  signText:{
    textAlign:"right",
    marginBottom:10,
    paddingRight:15,
  },
  memberImg:{
    width:44,
    height:44
  },
  redSpecail:{
    position:"absolute",
    width:10,
    height:10,
    right:0,
    top:0,
    borderRadius:5,
    backgroundColor:"red"
  },
  nav:{
    height:64,
    paddingTop:20,
    flexDirection:"row",
    backgroundColor:'#f9f9f9',
  },
  navTitle:{
    height:44,
    flex:1,
    justifyContent:"center",
    alignItems:'center',
  },
  navLeftIcon:{
    width:60,
    height:44,
    justifyContent:"center",
    alignItems:'center',
  },
  navRightText:{
    width:60,
    height:44,
    justifyContent:"center",
    alignItems:'center',
  },
})
