import {StyleSheet,Dimensions} from 'react-native';
export const styles = StyleSheet.create({
  mainList:{
    flex:1,
    backgroundColor:'#fff',
    borderTopWidth:1,
    borderTopColor:'#eaeaea',
  },
  listView:{
    height:44,
    flexDirection:"row",
    borderBottomWidth:1,
    borderBottomColor:'#eaeaea',
    paddingLeft:15,
    paddingRight:15,
    backgroundColor:'#fff',
  },
  tabView:{
    backgroundColor:"#fff",
    position:"absolute",
    top:0,
    left:0,
    borderTopWidth:0,
    borderBottomWidth:1,
    borderBottomColor:'#eaeaea',
  },
  listInput:{
    flex:2,
    justifyContent:"center",
    alignItems:'flex-start',
  },
  listViewText:{
    justifyContent:"center",
    alignItems:'flex-start',
    flex:1.6,
  },
  listViewText2:{
    justifyContent:"center",
    alignItems:'flex-start',
    flex:3,
  },
  tabBar:{
    height:40,
    justifyContent:"center",
    alignItems:'center',
  },
  tabListView:{
    marginTop:50,
  },
  marginTop50:{
    marginTop:50,
  },
  listCenterText:{
    textAlign:'center',
  },
  viewText:{
    width:Dimensions.get('window').width-60,
    marginLeft:30,
    marginRight:30,
  },
  marginTop10:{
    marginTop:10,
  },
  flex:{
    height:260,
  },
  touchBtn:{
    width:Dimensions.get('window').width-30,
    height:40,
    alignItems:"center",
    justifyContent:"center",
    backgroundColor:"#3a8ff3",
    borderRadius:6,
    marginLeft:15,
    marginRight:15,
    marginTop:25,
    marginBottom:25,
  },
});
