import {StyleSheet,Dimensions} from 'react-native';
export const styles = StyleSheet.create({
  mainView:{
    flex:1,
    backgroundColor:'#f7f8fa',
  },
  scrollView:{
    marginBottom:55,
  },
  bgImg:{
    width:Dimensions.get('window').width,
  },
  topView:{
    flexDirection:"row",
    justifyContent:"flex-end",
    alignItems:"center",
    marginTop:10,
    position:"absolute",
    top:10,
    right:0,
    height:40,
  },
  TopTouch1:{
    width:40,
    height:40,
    alignItems:'flex-end',
    justifyContent:"center",
  },
  TopTouch2:{
    width:40,
    height:40,
    alignItems:'flex-start',
    justifyContent:"center",
    marginLeft:15,
  },
  middleView:{
    alignItems:"center",
    marginTop:45,
  },
  middleTop:{
    flexDirection:"row",
    alignItems:"center",
    marginTop:10,
    backgroundColor:"transparent",
    height:32,
    justifyContent:"center",
  },
  middleBottom:{
    flexDirection:"row",
    marginBottom:5,
    marginTop:1,
    backgroundColor:"transparent"
  },
  bottomView:{
    height:40,
    backgroundColor:"rgba(92,89,88,0.7)",
    flexDirection:"row",
  },
  bottomTouch:{
    flex:1,
    justifyContent:"center",
    alignItems:"center",
  },
  bottomBoder:{
    paddingTop:7,
  },
  bottomL:{
    flexDirection:"row",
  },
  bottomImg:{
    marginRight:15,
    marginTop:3,
  },
  navTouch:{
    borderColor:"#f7f8fa",
    borderBottomWidth:1,
    backgroundColor:"#fff",
    height:44,
    alignItems:"center",
    paddingLeft:15,
    paddingRight:15,
    flexDirection:"row"
  },
  navText:{
    flex:1,
    paddingLeft:10,
  },
  marginLeft10:{
    marginLeft:7,
  },
  navMiddle:{
    paddingTop:19,
    paddingBottom:19,
    paddingLeft:25,
    paddingRight:25,
    flexDirection:"row",
    flexWrap:"wrap",
    backgroundColor:"#fff",
    marginTop:20,
    elevation: 20,
    shadowOffset: {width: 0, height: 0},
    shadowColor: 'rgba(92,89,88,0.7)',
    shadowOpacity: 1,
  },
  navView:{
    borderColor:"#f7f8fa",
    borderRightWidth:1,
    borderBottomWidth:1,
    width:(Dimensions.get('window').width-50)/3,
    alignItems:"center",
    backgroundColor:"#fff",
    paddingBottom:17,
  },
  navViewText:{
    marginTop:13,
  },
  borderNone:{
    borderBottomWidth:0,
    paddingTop:19,
  },
  borderRightNone:{
    borderRightWidth:0
  },
  myPhoto:{
    width:64,
    height:64,
  },
   marLR:{
     marginLeft:5,
     marginRight:5,
   },
   aboutImg:{
     width:Dimensions.get('window').width,
   },
   hasPic:{
     width:64,
     height:64,
     borderRadius:32
   },
   tabView:{
     alignItems:"center",
     backgroundColor:"#f9f9f9",
     width:Dimensions.get('window').width,
     position:"relative"
   },
   tabsContainerStyle:{
     backgroundColor:"#f9f9f9",
     height:44,
   },
   tabStyle:{
     borderWidth:0,
     borderRadius:0,
     backgroundColor:"#f9f9f9",
   },
   tabTextStyle:{

   },
   activeTabStyle:{
     backgroundColor:"#f9f9f9",
     borderRadius:0,
   },
   activeTabTextStyle:{
     color:"#3a8ff3"
   },
   redIconView:{
     position:"relative",
   },
   redIcon:{
     width:10,
     height:10,
     backgroundColor:'red',
     position:'absolute',
     right:10,
     top:5,
     borderRadius:5,
   },
});
