import {StyleSheet,Dimensions} from 'react-native';
export const styles = StyleSheet.create({
  main:{
    flex:1,
  },
  nav:{
    height:64,
    paddingTop:20,
    backgroundColor:'transparent',
    position:"absolute",
    top:0,
    left:0,
    width:Dimensions.get('window').width,
  },
  imgBg:{
    width:Dimensions.get('window').width,
    height:Dimensions.get('window').height,
  },
  navTitle:{
    height:44,
    lineHeight:44,
    textAlign:'center',
    backgroundColor:'transparent',
  },
  navIcon:{
    width:60,
    height:44,
    justifyContent:"center",
    alignItems:'flex-start',
    position:'absolute',
    left:0,
    top:20,
    zIndex:10,
    paddingLeft:15,
  },
  QRView:{
    alignItems:'center',
    marginTop:114,
  },
  promotionText:{
    justifyContent:"center",
    alignItems:'center',
    backgroundColor:'transparent',
  },
  exText:{
    fontWeight:'bold',
    marginTop:8,
    marginBottom:10,
  },
  text:{
    paddingLeft:10,
    paddingRight:10,
    lineHeight:24,
    fontWeight:'bold',
  },
  telText:{
    color:'#c8a063',
  },
  bold:{
    fontWeight:'bold',
  },
  QRCode:{
    width:140,
    height:140,
  },
  listBtn:{
    width:Dimensions.get('window').width-30,
    marginLeft:15,
    marginRight:15,
    justifyContent:"center",
    alignItems:'center',
    borderRadius: 6,
    height:40,
    backgroundColor:'#3a8ff3',
    marginTop:30,
  },

  mask:{
    flex:1,
    backgroundColor:'rgba(0,0,0,0.7)',
    justifyContent:"flex-end"
  },
  maskMain:{

  },
  closeBtn:{
    height:40,
    backgroundColor:'#fff',
    width:Dimensions.get('window').width,
    marginTop:10,
    justifyContent:"center",
    alignItems:'center',
  },
  share:{
    flexDirection:"row",
    paddingTop:10,
    paddingBottom:10,
    backgroundColor:'#fff',
  },
  shareView:{
    flex:1,
    justifyContent:"center",
    alignItems:'center',
  },
  shareText:{
    marginTop:15,
  },
  codeImg:{
    alignItems:"center",
    justifyContent:"flex-start"
  },
  specailText:{
    color:"#c8a063",
    marginTop:20,
    fontWeight:'bold',
  },
  codeText:{
    backgroundColor:"#fff",
    marginTop:20,
    textAlign:"center",
  },
  code:{
    width:167,
    height:167,
    marginTop:19,
  }
});
