import {StyleSheet,Dimensions} from 'react-native';
export const styles = StyleSheet.create({
  container:{
    flex:1,
    backgroundColor:'#fff',
    position:"relative"
  },
  touchBack:{
    position:"absolute",
    left:0,
    top:0,
    width:70,
    height:70,
    backgroundColor:"transparent",
    alignItems:"center",
    justifyContent:"center",
    zIndex:0,
  },
  bottomTouch:{
    flexDirection:"row",
    width:Dimensions.get('window').width,
    height:50,
    backgroundColor:"#fff",
    borderColor:"#eaeaea",
    borderTopWidth:1,
  },
  reportBtn:{
    height:50,
    alignItems:"center",
    justifyContent:"center",
    backgroundColor:"#3a8ff3",
    flex:1,
  },
  attention:{
    paddingRight:15,
    paddingLeft:15,
    alignItems:"center",
    borderColor:"#eaeaea",
    borderRightWidth:1,
    marginTop:8,
  },
  attention1:{
    alignItems:"center",
    marginTop:8,
    paddingRight:2,
    paddingLeft:2,
  },
  webView:{
    flex:1,
    borderWidth:0,
    borderColor:'transparent',
    backgroundColor:'#fff',
    height:600,
  },
  mt10:{
    marginTop:2,
  },
  mask:{
    flex:1,
    backgroundColor:'rgba(0,0,0,0.7)',
    justifyContent:"flex-end"
  },
  closeBtn:{
    height:40,
    backgroundColor:'#fff',
    width:Dimensions.get('window').width,
    marginTop:10,
    justifyContent:"center",
    alignItems:'center',
  },
  share:{
    flexDirection:"row",
    paddingTop:10,
    paddingBottom:10,
    backgroundColor:'#fff',
  },
  shareView:{
    flex:1,
    justifyContent:"center",
    alignItems:'center',
  },
  shareText:{
    marginTop:15,
  },


});
