import {StyleSheet,Dimensions} from 'react-native';
export const styles = StyleSheet.create({
  container:{
    flex:1,
    backgroundColor:'#fff',
    position:"relative",
  },
  nav:{
    height:64,
    width:Dimensions.get('window').width,
    paddingTop:20,
    backgroundColor:"transparent",
    position:'absolute',
    left:0,
    top:0,
  },
  navLeft:{
    width:60,
    height:60,
    justifyContent:"center",
    position:"absolute",
    left:0,
    top:0,
    zIndex:0,
    paddingTop:15,
    paddingLeft:15,
  },
  touchBack:{
    width:60,
    height:60,
    justifyContent:"center",
    position:"absolute",
    left:0,
    top:0,
    zIndex:0,
    paddingTop:15,
    paddingLeft:15,
  },
  navName:{
    width:Dimensions.get('window').width-120,
    textAlign:'center',
  },
  swiper:{
    height:220,
    marginBottom:10,
  },
  slide:{
    position:"relative",
  },
  slideImg:{
    width:Dimensions.get('window').width,
    height:220,
  },
  slideTxt:{
    width:Dimensions.get('window').width,
    height:32,
    backgroundColor:'rgba(0,0,0,0.7)',
    paddingLeft:15,
    paddingRight:15,
    position:'absolute',
    left:0,
    bottom:0,
    alignItems:"flex-start",
    justifyContent:"center",
  },
  slideTxtT:{
    width:Dimensions.get('window').width-60,
  },
  paginationStyle:{
    position:'absolute',
    right:15,
    bottom:0,
    backgroundColor:'transparent',
    alignItems:"flex-end",
    justifyContent:"center",
    height:32,
  },
  main:{
    backgroundColor:'#f7f8fa',
    flex:1,
  },
  label:{
    flexWrap:'wrap',
    flexDirection:"row",
    paddingRight:15,
    paddingLeft:15,
    backgroundColor:"#fff",
  },
  flag:{
    borderWidth:1,
    marginRight:10,
    paddingTop:2,
    paddingLeft:5,
    paddingBottom:2,
    paddingRight:5,
  },
  flagColor1:{
    borderColor:"#f38181",
  },
  txtColor1:{
    color:"#f38181",
  },
  flagColor2:{
    borderColor:"#a9eee6",
  },
  txtColor2:{
    color:"#a9eee6",
  },
  flagColor3:{
    borderColor:"#ffd181",
  },
  txtColor3:{
    color:"#ffd181",
  },
  price:{
    paddingRight:15,
    paddingLeft:15,
    backgroundColor:'#fff',
  },
  txtRed:{
    color:"#f23c3c",
  },
  information:{
    paddingRight:15,
    paddingLeft:15,
    backgroundColor:'#fff',
    paddingBottom:15,
  },
  marginTop5:{
    marginTop:5,
  },
  marginTop8:{
    marginTop:8,
  },
  marginTop10:{
    marginTop:10,
  },
  lineHeight22:{
    lineHeight:22,
  },
  marginBottom50:{
    marginBottom:50,
  },
  marginBottom20:{
    marginBottom:50,
    marginTop:-20
  },
  paddingRight15:{
    paddingRight:15,
  },
  title:{
    height:40,
    flexDirection:"row",
    alignItems:"center",
    justifyContent:"center",
  },
  titleLeft:{
    flex:1,
  },
  commission:{
    paddingRight:15,
    paddingLeft:15,
    backgroundColor:'#fff',
    marginTop:15,
    paddingBottom:15,
  },
  infoOverview:{
    paddingRight:15,
    paddingLeft:15,
    backgroundColor:'#fff',
    marginTop:15,
    paddingBottom:15,
  },
  floorplan:{
    height:44,
    flexDirection:"row",
    alignItems:"center",
    justifyContent:"center",
    borderTopWidth:1,
    borderBottomWidth:1,
    borderColor:'#eaeaea',
    paddingRight:15,
    paddingLeft:15,
    backgroundColor:'#fff',
  },
  floorplanTxt:{
    fontWeight:'bold',
    color:'#488ae4',
  },
  recommend:{
    paddingLeft:15,
    backgroundColor:'#fff',
    paddingBottom:15,
  },
  recommendMain:{
    flexDirection:"row",
  },
  recommendView:{
    width:150,
    marginRight:12,
  },
  recommendImg:{
    width:150,
    height:100,
  },
  bottomTouch:{
    flexDirection:"row",
    width:Dimensions.get('window').width,
    height:50,
    backgroundColor:"#fff",
    borderColor:"#eaeaea",
    borderTopWidth:1,
    position:'absolute',
    left:0,
    bottom:0,
  },
  reportBtn:{
    height:50,
    alignItems:"center",
    justifyContent:"center",
    backgroundColor:"#3a8ff3",
    flex:1,
  },
  attention:{
    paddingRight:15,
    paddingLeft:15,
    alignItems:"center",
    borderColor:"#eaeaea",
    borderRightWidth:1,
    marginTop:8,
  },
  attention1:{
    alignItems:"center",
    marginTop:8,
    paddingRight:2,
    paddingLeft:2,
  },
  webView:{
    flex:1,
    borderWidth:0,
    borderColor:'transparent',
    backgroundColor:'#fff',
    height:600,
  },
  mt10:{
    marginTop:2,
  },
  mask:{
    flex:1,
    backgroundColor:'rgba(0,0,0,0.7)',
    justifyContent:"flex-end"
  },
  closeBtn:{
    height:40,
    backgroundColor:'#fff',
    width:Dimensions.get('window').width,
    marginTop:10,
    justifyContent:"center",
    alignItems:'center',
  },
  share:{
    flexDirection:"row",
    paddingTop:10,
    paddingBottom:10,
    backgroundColor:'#fff',
  },
  shareView:{
    flex:1,
    justifyContent:"center",
    alignItems:'center',
  },
  shareText:{
    marginTop:15,
  },


  viewList:{
    borderBottomWidth:1,
    borderColor:'#eaeaea',
    justifyContent:"center",
    alignItems:'flex-start',
    backgroundColor:'#fff',
    paddingRight:15,
    paddingLeft:15,
    paddingTop:10,
    paddingBottom:10,
  },
  webView:{
    width:Dimensions.get('window').width-30,
    marginRight:15,
    marginLeft:15,
    flex:1,
    height:"auto",
    minHeight:600,
  },
  flexView:{
    flexDirection:"row",
  },
  flexText:{
    flex:1,
  },
  more:{
    width:50,
    height:40,
    alignItems:"center",
  },
  swiperMask:{
    flex:1,
    backgroundColor:'#010101',
    justifyContent:"center",
    alignItems:'center',
  },
  swiperMaskNav:{
    width:Dimensions.get('window').width,
    height:64,
    backgroundColor:'#141414',
    flexDirection:"row",
    paddingTop:20,
  },
  swiperMasknavLeft:{
    width:60,
    height:44,
    backgroundColor:'transparent',
    justifyContent:"center",
    alignItems:'flex-start',
    paddingLeft:15,
  },
  swiperMasknavCenter:{
    width:Dimensions.get('window').width-120,
    height:44,
    backgroundColor:'transparent',
    justifyContent:"center",
    alignItems:'center',
  },
  swiperMaskMain:{
    flex:1,
    backgroundColor:'#010101',
    justifyContent:"center",
    alignItems:'center',
  },
  swiper1:{
    height:300,
    width:Dimensions.get('window').width,
  },
  slideImg1:{
    width:Dimensions.get('window').width,
    height:250,
  },
  paginationStyle1:{
    height:20,
    marginTop:30,
    justifyContent:"center",
    alignItems:'center',
  },
  marginTop15:{
    marginTop:10,
  }










});
