import {StyleSheet,Dimensions} from 'react-native';
export const styles = StyleSheet.create({
  container:{
    flex:1,
    backgroundColor:"#f7f8fa",
  },
  featured:{
    backgroundColor:"#f7f8fa",
  },
  swiper:{
    height:240,
  },
  slideImg:{
    width:Dimensions.get('window').width,
    height:240,
  },
  topView:{
    height:64,
    flexDirection:"row",
    width:Dimensions.get('window').width,
    backgroundColor:'#fff',
    paddingTop:20,
  },
  SearchBtn:{
    flex:4,
    marginRight:10,
    height:30,
    alignItems:"flex-start",
    justifyContent:"center",
    marginTop:5,
    marginBottom:5,
    backgroundColor:"#f7f8fa",
  },
  SearchIcon:{
    marginLeft:10,
    marginRight:10,
  },
  chooseCity:{
    flexDirection:"row",
    paddingLeft:10,
    paddingRight:14,
    height:30,
    marginTop:5,
    backgroundColor:"#fff",
    alignItems:"center",
    justifyContent:"center",
    marginLeft:10,
  },
  chooseText:{
    marginRight:5,
  },
  middleTouch:{
    marginRight:5,
    backgroundColor:"#fff",
    marginTop:5,
    paddingRight:15,
    paddingTop:6,
  },
  BottomView:{
    backgroundColor:"#fff",
    flexDirection:"row",
    paddingLeft:20,
    paddingRight:20,
    paddingTop:19,
    paddingBottom:21,
  },
  touchBtn:{
    width:(Dimensions.get('window').width-40)/3,
    alignItems:"center",
    justifyContent:"center",
  },
  touchBtn1:{
    width:(Dimensions.get('window').width-40)/3,
    alignItems:"flex-start",
    justifyContent:"center",
  },
  touchBtn2:{
    width:(Dimensions.get('window').width-40)/3,
    alignItems:"flex-end",
    justifyContent:"center",
  },
  touchView:{
    alignItems:"center",
    justifyContent:"center",
  },
  textTop:{
    marginTop:8,
  },
  MiddleView:{
    backgroundColor:"#fff",
    flexDirection:"row",
    paddingTop:20,
    alignItems:"center",
    justifyContent:"center",
  },
  textView:{
    width:(Dimensions.get('window').width-40)/3,
    alignItems:"center",
    justifyContent:"center",
  },
  textView1:{
    width:(Dimensions.get('window').width-40)/3,
    alignItems:"flex-start",
    justifyContent:"center",
    borderRightWidth:1,
    borderColor:"#eaeaea",
    paddingLeft:10,
  },
  textView2:{
    width:(Dimensions.get('window').width-40)/3,
    alignItems:"flex-end",
    justifyContent:"center",
    borderLeftWidth:1,
    borderColor:"#eaeaea",
    paddingRight:10
  },
  textNum:{
    color:"#fe8686",
    fontSize:16,
  },
  newsView:{
    flexDirection:"row",
    paddingRight:10,
    paddingLeft:10,
    paddingTop:14,
    paddingBottom:14,
    backgroundColor:"#fff",
  },
  projectTitle:{
    flexDirection:"row",
    justifyContent:"flex-start",
    paddingTop:15,
    paddingBottom:15,
    paddingLeft:10,
    backgroundColor:"#fff",
    borderBottomWidth:1,
    borderColor:"#eaeaea",
    marginTop:6
  },
  titleWeight:{
    flex:1
  },
  searchRight:{
    position:"absolute",
    right:15,
    bottom:15,
    zIndex:20
  },
  modalMask:{
    backgroundColor:'#f7f8fa',
    flex:1,
    justifyContent:"flex-start",
    alignItems:'center',
  },
  centerView:{
    width:Dimensions.get('window').width,
    flex:1,
  },
  searchTop:{
    height:60,
    flexDirection:"row",
    paddingLeft:15,
    paddingRight:10,
    backgroundColor:"#fff",
    paddingTop:23,
  },
  searchInput:{
    height:30,
    alignItems:"center",
    justifyContent:"center",
    backgroundColor:"#f7f8fa",
    borderRadius:10,
    flex:1,
    flexDirection:"row",
    paddingLeft:5,
  },
  searchIputRest:{
    flex:1,
    padding:0,
    margin:0,
    marginLeft:10,
  },
  cancelBtn:{
    alignItems:"center",
    justifyContent:"center",
    paddingBottom:8,
    paddingLeft:15,
  },
  historyView:{
    paddingTop:15,
    backgroundColor:"#fff",
  },
  historyViewSon:{
    flexDirection:"row",
    paddingLeft:15,
    paddingRight:15,
    borderBottomWidth:1,
    borderColor:"#ececec",
    paddingTop:10,
    paddingBottom:10,
  },
  historyText:{
    flex:3,
  },
  delectTouch:{
    flex:6,
    alignItems:"flex-start",
  },
  delectTouchRest:{
    flex:1,
    alignItems:"flex-end",
  },

});
