import {StyleSheet,Dimensions} from 'react-native';
export const styles = StyleSheet.create({
  mainView:{
    flex:1,
    backgroundColor:"#f7f8fa",
  },
  view:{
    marginBottom:10,
    backgroundColor:'#fff',
    marginBottom:10,
  },
  view1:{
    width:Dimensions.get('window').width,
    paddingLeft:15,
    paddingRight:15,
    backgroundColor:"#fff",
    flexDirection:"row",
    position:"relative"
  },
  viewLeft:{
    width:100,
  },
  viewLeftList:{
    marginBottom:30,
  },
  viewRight:{
    flex:1,
    borderLeftWidth:1,
    borderLeftColor:"#eaeaea",
  },
  viewRightList:{
    paddingLeft:20,
    marginBottom:30,
  },
  viewRightIcon:{
    position:"absolute",
    left:3,
    top:0,
    width:14,
    height:14,
    zIndex:10,
  },
  red:{
    color:"#ec0101",
  },
  viewEnd:{
    marginBottom:0,
  },
  marginBottom5:{
    marginBottom:5,
  },
  marginBottom10:{
    marginBottom:10,
    textAlignVertical:"top",
    includeFontPadding:false
  },
  marginBottom15:{
    marginBottom:13,
  },
  ListTextNum:{
    flexDirection:"row",
    paddingLeft:15,
    paddingRight:15,
    paddingTop:15,
    paddingBottom:15,
  },
  project:{
    flex:1,
    marginLeft:8,
  },
  projectText:{
    marginBottom:10,
  },
  viewList:{
    backgroundColor:"#fff",
    borderBottomWidth:1,
    borderBottomColor:'#eaeaea',
    paddingLeft:15,
    paddingRight:15,
    paddingTop:10,
    paddingBottom:10,
  },
  viewListDate:{
    marginTop:10,
  },
  nav:{
    height:64,
    paddingTop:20,
    backgroundColor:'transparent',
    marginLeft:15,
    marginRight:15,
    flexDirection:"row",
    justifyContent:"center",
    alignItems:'center',
  },
  navCenter:{
    flex:1,
    justifyContent:"center",
    alignItems:'center',
  },
  navRight:{
    borderWidth:1,
    borderColor:'#ed6c5f',
    justifyContent:"center",
    alignItems:'center',
    width:56,
    height:26,
    borderRadius:3,
  },
  titleView:{
    height:45,
    paddingLeft:15,
    paddingRight:15,
    borderBottomWidth:1,
    borderBottomColor:'#eaeaea',
    justifyContent:"flex-start",
    alignItems:'center',
    flexDirection:"row",
  },
  rightTitle:{
    flex:1,
    flexDirection:"row",
    justifyContent:"flex-end",
    alignItems:'center',
  },
  rightTitleText:{
    marginRight:10,
    marginLeft:5,
  },
  titleViewText:{
    marginLeft:5
  },
  listView:{
    flexDirection:"row",
    height:200,
    width:Dimensions.get('window').width,
    backgroundColor:"red"
  },
  listLeft:{
    flex:1,
  },
  listMiddle:{
    flex:1,
  },
  listRight:{
    flex:2,
  },
  flowsView:{
    backgroundColor:"#fff",
    paddingTop:20,
    borderBottomColor:"#eaeaea",
    borderBottomWidth:1,
    paddingBottom:10,
  },
  newView:{
    flex:1,
    backgroundColor:"#fff",
    paddingTop:20,
  },
  list:{
    paddingTop:20,
    backgroundColor:"#fff"
  }
});
