import {StyleSheet,Dimensions} from 'react-native';
export const styles = StyleSheet.create({
  main:{
    flex:1,
    backgroundColor:'#f7f8fa',
  },
  nav:{
    width:Dimensions.get('window').width,
    height:64,
    backgroundColor:'#f9f9f9',
    flexDirection:"row",
    paddingTop:20,
    borderBottomWidth:1,
    borderBottomColor:"#eaeaea"
  },
  navLeft:{
    width:60,
    height:44,
    backgroundColor:'transparent',
    justifyContent:"center",
    alignItems:'flex-start',
    paddingLeft:15,
  },
  navCenter:{
    width:Dimensions.get('window').width-180,
    height:44,
    backgroundColor:'transparent',
    justifyContent:"center",
    alignItems:'center',
    marginLeft:30,
  },
  navRight:{
    width:90,
    height:44,
    backgroundColor:'transparent',
    justifyContent:"center",
    alignItems:'center',
    flexDirection:"row",
  },
  navRightIcon:{
    marginLeft:5,
  },
  chartBg: {
    width:Dimensions.get('window').width-30,
    marginLeft:15,
    marginRight:15,
    height: 260,
    marginTop:10,
	},
  chartMain:{
    flexDirection:"row",
  },
  chartView:{
    width: 240,
		height: 160,
    justifyContent: 'center',
		alignItems: 'center',
		backgroundColor: 'transparent',
  },
  chartViewTxt:{
    width:230,
    height:20,
    paddingLeft:15,
    flexDirection:"row",
    marginLeft:48,
  },
  chartViewTxtD:{
    justifyContent: 'center',
		alignItems: 'center',
    paddingLeft:17,
  },
	chart: {
		width: 230,
		height: 150,
    backgroundColor:"transparent"
	},
  chartTitle:{
    width:Dimensions.get('window').width-30,
    height:40,
    justifyContent: 'center',
		alignItems: 'center',
    backgroundColor:"transparent",
    marginTop:5,
  },
  chartTitleTxt:{
    backgroundColor:"transparent",
    fontWeight:"bold"
  },
  chartTxt:{
    flex:1,
    justifyContent: 'flex-end',
		alignItems: 'center',
    marginBottom:15,
  },
  chartTxtTxt:{
    backgroundColor:"transparent",
    marginBottom:10,
  },
  chartBgTxtColor1:{
    color:"#21b2fc",
  },
  chartBgTxtColor2:{
    color:"#7275ff",
  },
  chartBgTxt:{
    width:Dimensions.get('window').width-30,
    marginTop:10,
    flexDirection:"row",
    height:40,
    backgroundColor:"transparent",
    paddingLeft:15,
    paddingRight:15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  chartBgTxtL:{
    flex:1,
    textAlign:"left",
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  chartBgTxtR:{
    flex:1,
    textAlign:"right",
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  mask:{
    flex:1,
    backgroundColor:'rgba(0,0,0,0.7)',
    justifyContent:"flex-start",
    alignItems:'center',
  },
  maskMain:{
    width:Dimensions.get('window').width,
    backgroundColor:"#fff",
  },
  timeList:{
    height:45,
    borderBottomWidth:1,
    borderBottomColor:"#eaeaea",
    paddingLeft:15,
    paddingRight:15,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  timeListPersonality:{
    width:Dimensions.get('window').width,
    height:45,
    borderBottomWidth:1,
    borderBottomColor:"#eaeaea",
    paddingLeft:15,
    paddingRight:15,
    flexDirection:"row",
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  listInput:{
    width:90,
    height:20,
    borderColor:"#eaeaea",
    borderWidth:1,
    marginLeft:5,
    marginRight:5,
    lineHeight:18,
    padding:0,
    paddingLeft:5,
    paddingRight:5
  },
  timeBtn:{
    width:Dimensions.get('window').width,
    height:45,
    borderBottomWidth:1,
    borderBottomColor:"#eaeaea",
    paddingLeft:15,
    paddingRight:15,
    flexDirection:"row",
    justifyContent: 'center',
    alignItems: 'center',
  },
  timeBtnL:{
    width:150,
    height:24,
    borderWidth:1,
    borderColor:"#eaeaea",
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius:4,
  },
  timeBtnR:{
    width:150,
    height:24,
    borderWidth:1,
    borderColor:"#3a8ff3",
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft:20,
    borderRadius:4,
  },
});
