import {StyleSheet,Dimensions} from 'react-native';
export const styles = StyleSheet.create({
  main:{
    flex:1,
    backgroundColor:'#f7f8fa',
  },
  view:{
    backgroundColor:"#fff",
    borderBottomColor:"#eaeaea",
    borderBottomWidth:1,
  },
  title:{
    height:44,
    flexDirection:"row",
    paddingLeft:15,
    paddingRight:15,
    backgroundColor:'#fff',
    justifyContent:"center",
    alignItems:'center',
  },
  titleText:{
    flex:1,
  },
  addText:{
    paddingLeft:15,
    paddingRight:15,
    paddingBottom:10,
  },
  addImg:{
    marginLeft:15,
    marginRight:15,
    width:Dimensions.get('window').width-30,
    height:140,
    justifyContent:"center",
    alignItems:'center',
    backgroundColor:'#fff'
  },
  selectIcon:{
    marginLeft:5,
    marginTop:5,
  },
  numView:{
    flexDirection:"row",
    paddingLeft:15,
    paddingRight:15,
  },
  numViewText:{
    lineHeight:40,
  },
  numViewInput:{
    borderWidth:1,
    borderColor:'#eaeaea',
    height:40,
    width:140,
    backgroundColor:'#fff',
    borderRadius:6,
    paddingLeft:5,
  },
  viewBtn:{
    flexDirection:"row",
    position:'absolute',
    bottom:10,
    paddingLeft:15,
    paddingRight:15,
    backgroundColor:"#fff"
  },
  listBtn2:{
    flex:1,
    justifyContent:"center",
    alignItems:'center',
    borderRadius: 6,
    height:40,
    backgroundColor:'#3a8ff3',
  },
  marginLeft15:{
    marginLeft:15,
  },
  listNoBtn2:{
    flex:1,
    justifyContent:"center",
    alignItems:'center',
    borderRadius: 6,
    height:40,
    borderWidth:1,
    borderColor:'#898989',
  },
  newView:{
  },
  remarks:{
    paddingLeft:15,
    paddingRight:15,
    paddingTop:15,
    backgroundColor:"#fff",
    flex:1,
  },
  remarksInput:{
    height:140,
    marginTop:10,
    backgroundColor:'#fff',
    borderRadius:6,
    paddingLeft:10,
    paddingRight:10,
    paddingTop:10,
    paddingBottom:10,
    textAlignVertical:"top",
    borderWidth:1,
    borderColor:"#eaeaea"
  },
  lineView:{
    backgroundColor:"#f7f8fa",
    height:10,
  },
  nav:{
    height:64,
    paddingTop:20,
    backgroundColor:'transparent',
    marginLeft:15,
    marginRight:15,
    flexDirection:"row",
    justifyContent:"center",
    alignItems:'center',
  },
  navCenter:{
    flex:1,
    justifyContent:"center",
    alignItems:'center',
  },
  navRight:{
    borderWidth:1,
    borderColor:'#ed6c5f',
    justifyContent:"center",
    alignItems:'center',
    width:56,
    height:26,
    borderRadius:3,
  },
});
