import {StyleSheet,Dimensions} from 'react-native';
export const styles = StyleSheet.create({
  main:{
    flex:1,
    backgroundColor:'#f7f8fa',
  },
  nav:{
    height:64,
    paddingTop:20,
    flexDirection:"row",
    backgroundColor:'#f9f9f9',
    borderBottomWidth:1,
    borderBottomColor:"#eaeaea"
  },
  navTitle:{
    height:44,
    flex:1,
    justifyContent:"center",
    alignItems:'center',
  },
  navLeftIcon:{
    width:60,
    height:44,
    justifyContent:"center",
    alignItems:'flex-start',
    paddingLeft:15,
  },
  navRightText:{
    width:60,
    height:44,
    justifyContent:"center",
    alignItems:'flex-end',
    paddingRight:15
  },
  tabView:{
    backgroundColor:"#fff",
    position:"absolute",
    top:-1,
    left:0,
    borderTopWidth:0,
    borderBottomWidth:1,
    borderBottomColor:'#eaeaea',
  },
  tabBar:{
    height:40,
  },
  listView:{
    height:44,
    flexDirection:"row",
    borderBottomWidth:1,
    borderBottomColor:'#eaeaea',
    paddingLeft:15,
    paddingRight:15,
    backgroundColor:'#fff',
    justifyContent:"center",
    alignItems:'center',
  },
  listViewText:{
    alignItems:"center"
  },
  listInput:{
    flex:1,
  },
  text:{
    marginLeft:15,
    marginRight:15,
    marginTop:10,
  },
  btn:{
    position:'absolute',
    bottom:-30,
  },
  listBtn:{
    width:Dimensions.get('window').width-30,
    marginLeft:15,
    marginRight:15,
    justifyContent:"center",
    alignItems:'center',
    borderRadius: 6,
    height:40,
    backgroundColor:'#3a8ff3',
  },
  listBtnRest:{
    position:"absolute",
    bottom:20,
    left:0,
  },
  listNoBtn:{
    width:Dimensions.get('window').width-30,
    marginLeft:15,
    marginRight:15,
    justifyContent:"center",
    alignItems:'center',
    borderRadius: 6,
    height:40,
    borderWidth:1,
    borderColor:'#898989',
    marginTop:10,
  },
  listViewRest:{
    marginTop:10,
    height:140,
    backgroundColor:"#fff",
    borderWidth:0
  },
  listViewTextRest:{
    alignSelf:"flex-start",
    paddingTop:7,
  },
  moreInput:{
    borderWidth:0
  },
  radioView:{
    flex:1,
  },
  viewBtn:{
    flexDirection:"row",
    marginTop:20,
    paddingLeft:15,
    paddingRight:15,
    marginBottom:20,
  },
  listBtn2:{
    flex:1,
    justifyContent:"center",
    alignItems:'center',
    borderRadius: 6,
    height:40,
    backgroundColor:'#3a8ff3',
    marginLeft:15,
  },
  listNoBtn2:{
    flex:1,
    justifyContent:"center",
    alignItems:'center',
    borderRadius: 6,
    height:40,
    borderWidth:1,
    borderColor:'#898989',
  },
  borderView:{
    borderColor:"#eaeaea",
    borderTopWidth:1
  },
  enterView:{
    flexDirection:"row",
    paddingTop:14,
    paddingBottom:14,
    paddingLeft:15,
    paddingRight:15,
    backgroundColor:"#fff"
  },
  enterTitle:{
    flex:1,
  },
  enterBtn:{
    flexDirection:"row"
  },
  mt10:{
    marginTop:10,
  },
  bzView:{
    marginLeft:15,
    marginRight:15,
    paddingTop:25,
    marginBottom:80,
  },
  newlistView:{
    marginTop:12,
    height:140,
    backgroundColor:"#fff",
    borderRadius:3,
    borderColor:"#eaeaea",
    borderWidth:1,
  },
  inputPadding:{
    paddingTop:15,
    paddingBottom:15,
    paddingLeft:7,
    paddingRight:7
  },
  imgMl:{
    marginLeft:7
  },
  checkView:{
    flex:1,
    flexDirection:"row"
  },
  checkBoxView:{
    width:100
  },
  signTitleView:{
    flexDirection:"row",
    backgroundColor:"#f9f9f9",
    height:65,
    alignItems:"center",
    justifyContent:"center",
    borderColor:"#eaeaea",
    borderBottomWidth:1,
    paddingTop:15,
  },
  backView:{
    width:60,
    height:60,
    alignItems:"center",
    justifyContent:"center",
    position:"absolute",
    left:0,
    top:0,
    zIndex:10,
    paddingTop:15,
  },
  searchView:{
    width:60,
    height:60,
    alignItems:"center",
    justifyContent:"center",
    position:"absolute",
    right:0,
    top:0,
    zIndex:10,
    paddingTop:15,
  },
  reportState:{
    alignItems:"center",
    justifyContent:"center",
    paddingTop:10,
    paddingBottom:10,
  },
  reportView:{
    flexDirection:"row",
    alignItems:"center",
    justifyContent:"center",
    paddingBottom:5,
  },
  flexView:{
    flex:1,
    textAlign:"center"
  },
  flexRowView:{
    flexDirection:"row",
  },
  radioView1:{
    alignItems:"flex-start",
    justifyContent:"flex-start",
    backgroundColor:"#fff",
  },
  radioViewBtn:{
    borderColor:"#eaeaea",
    borderBottomWidth:1,
    paddingTop:10,
    paddingBottom:10,
    paddingLeft:15,
    paddingRight:15,
    backgroundColor:"#fff",
    width:Dimensions.get('window').width
  },
  flexLabel:{
    flex:3,
    height:40,
    justifyContent:"center",
  },
  drowViewBtn:{
    flexDirection:"row",
    backgroundColor:"#fff",
    marginTop:10,
    height:40,
    alignItems:"center",
    justifyContent:"center",
    paddingLeft:15,
    paddingRight:15,
    borderColor:"#eaeaea",
    borderTopWidth:1,
    borderBottomWidth:1
  },
  textInputValue:{
    height:40,
    borderWidth:0,
    alignItems:"center"
  },
  error:{
    paddingLeft:15,
    paddingTop:15,
    paddingBottom:15,
  },
});
