import {StyleSheet,Dimensions} from 'react-native';
export const styles = StyleSheet.create({
  mainView:{
    flex:1,
    backgroundColor:"#f7f8fa"
  },
  nav:{
    height:64,
    paddingTop:20,
    backgroundColor:'transparent',
    flexDirection:"row",
    justifyContent:"center",
    alignItems:'center',
  },
  navLeft:{
    height:44,
    width:60,
    justifyContent:"center",
    alignItems:'center',
  },
  navCenter:{
    flex:1,
    justifyContent:"center",
    alignItems:'center',
  },
  navC:{
    height:64,
    paddingTop:20,
    backgroundColor:'transparent',
    justifyContent:"center",
    alignItems:'center',
    position:'relative',
  },
  navLeftC:{
    height:44,
    width:60,
    justifyContent:"center",
    alignItems:'flex-start',
    position:'absolute',
    left:0,
    top:20,
    paddingLeft:15,
  },
  navCenterC:{
    width:Dimensions.get('window').width-120,
    marginLeft:60,
    marginRight:60,
    justifyContent:"center",
    alignItems:'center',
  },
  navRight:{
    borderWidth:1,
    borderColor:'#ed6c5f',
    justifyContent:"center",
    alignItems:'center',
    width:56,
    height:26,
    borderRadius:3,
  },
  view:{
    marginBottom:10,
    backgroundColor:'#fff',
    elevation: 2,
    shadowColor: "#050001",
    shadowOffset: { height: 1, width: 1 },
    shadowOpacity: .1,
    shadowRadius: 2,
  },
  titleView:{
    height:45,
    paddingLeft:15,
    paddingRight:15,
    borderBottomWidth:1,
    borderBottomColor:'#eaeaea',
    justifyContent:"flex-start",
    alignItems:'center',
    flexDirection:"row"
  },
  rightTitle:{
    flex:1,
    flexDirection:"row",
    justifyContent:"flex-end",
    alignItems:'center',
  },
  rightTitleText:{
    marginRight:10,
    marginLeft:5,
  },
  titleViewText:{
    marginLeft:5,
    fontWeight:"bold"
  },
  bodyView:{
    paddingLeft:15,
    paddingRight:15,
    paddingBottom:15,
  },
  bodyViewText:{
    marginTop:15,
  },
  row:{
    flexDirection:"row",
  },
  flex:{
    flex:1,
  },
  numBtn:{
    width:60,
    height:24,
    justifyContent:"center",
    alignItems:'center',
    borderRadius:3,
    borderWidth:1,
    borderColor:'#3a8ff3',
    marginTop:10,
  },
  numBtnNo:{
    width:70,
    height:25,
    justifyContent:"center",
    alignItems:'center',
    borderRadius:3,
    borderWidth:1,
    borderColor:'#898989',
    marginLeft:10,
    marginRight:12
  },
  ListTextNum:{
    flexDirection:"row",
    paddingLeft:15,
    paddingRight:15,
    paddingTop:15,
    paddingBottom:15,
  },
  project:{
    flex:1,
    marginLeft:8,
  },
  projectText:{
    marginBottom:10,
  },
  marginBottom5:{
    marginBottom:5,
  },
  listBtn:{
    width:Dimensions.get('window').width-30,
    marginLeft:15,
    marginRight:15,
    justifyContent:"center",
    alignItems:'center',
    borderRadius: 6,
    height:40,
    backgroundColor:'#3a8ff3',
    marginTop:50,
    marginBottom:20,
  },
  bottomView:{
    height:50,
    backgroundColor:"#fff",
    alignItems:"center",
    flexDirection:"row",
    position:"absolute",
    bottom:0,
    left:0,
    width:Dimensions.get('window').width,
  },
  viewMore:{
    paddingLeft:5,
    paddingRight:5,
    borderWidth:1,
    borderColor:'#3a8ff3',
    borderRadius:3,
    marginRight:12,
    justifyContent:"center",
    alignItems:'center',
    height:25,
  },
  viewTextMore:{

  },
  numBtnNo1:{
    width:70,
    height:25,
    justifyContent:"center",
    alignItems:'center',
    borderRadius:3,
    marginLeft:10,
    marginRight:12
  },
  flowsView:{
    marginTop:15,
    paddingBottom:10,
  },
  view1:{
    marginBottom:50
  }
});
