import {StyleSheet,Dimensions} from 'react-native';
export const styles = StyleSheet.create({
  container:{
    flex:1,
    backgroundColor:"#f7f8fa",
  },
  searchView:{
    height:50,
    flexDirection:"row",
    backgroundColor:"#fff",
    alignItems:"center",
    paddingLeft:15,
    paddingRight:15,
    borderBottomColor:"#ececec",
    borderBottomWidth:1,
  },
  leftSearch:{
    borderRadius:15,
    backgroundColor:"#f7f8fa",
    height:30,
    paddingLeft:10,
    width:Dimensions.get('window').width-90,
    flexDirection:"row",
    alignItems:"center",
  },
  leftText:{
    color:"#ccc",
    fontSize:14,
    marginLeft:6,
  },
  rightSearch:{
    paddingLeft:10,
    width:60,
    flexDirection:"row",
    alignItems:"center",
    height:30,
  },
  tabView:{
    backgroundColor:"#fff",
    paddingTop:10,
    paddingBottom:10,
    borderBottomColor:"#eaeaea",
    borderBottomWidth:1,
    borderTopWidth:1,
    borderTopColor:"#eaeaea",
    marginTop:10,
    flexDirection:"row"
  },
  tabTouch:{
    width:Dimensions.get('window').width/6,
    alignItems:"center"
  },
  blueText:{
    marginBottom:5,
    color:"#7ab5ff",
    fontSize:14,
  },
  grayText:{
    color:"#aaaaaa",
    fontSize:14,
    marginBottom:5,
  },
  imgMt:{
    marginBottom:5,
  },
  touchView:{
    paddingLeft:15,
    paddingRight:15,
    paddingBottom:5
  },
  topView:{
    flexDirection:"row",
    marginTop:10,
  },
  flex:{
    flex:1
  },
  topRight:{
    flexDirection:"row",
    marginRight:19,
    alignItems:"center"
  },
  imgMr:{
    marginRight:5,
  },
  bottomView:{
    borderTopWidth:1,
    borderTopColor:"#eaeaea",
    height:38,
    justifyContent:"center",
    marginTop:10,
    borderBottomWidth:1,
    borderBottomColor:"#eaeaea",
    paddingLeft:15,
    paddingRight:15,
  },
  mt10:{
    marginTop:10,
  },
  textBold:{
    fontWeight:"bold"
  },
  modalMask:{
    backgroundColor:'#f7f8fa',
    flex:1,
    justifyContent:"flex-start",
    alignItems:'center',
  },
  centerView:{
    width:Dimensions.get('window').width,
    flex:1,
  },
  searchTop:{
    height:60,
    flexDirection:"row",
    paddingRight:15,
    backgroundColor:"#fff",
    paddingTop:23,
    borderBottomWidth:1,
    borderBottomColor:"#eaeaea"
  },
  searchInput:{
    height:30,
    alignItems:"center",
    justifyContent:"center",
    backgroundColor:"#f7f8fa",
    borderRadius:15,
    flex:1,
    flexDirection:"row",
    paddingLeft:5,
  },
  searchIputRest:{
    flex:1,
    padding:0,
    margin:0,
    marginLeft:10,
  },
  cancelBtn:{
    alignItems:"center",
    justifyContent:"center",
    paddingBottom:8,
    paddingLeft:15,
  },
  backView:{
    alignItems:"center",
    marginRight:10,
    paddingLeft:15,
    paddingTop:7,
  },
  downView:{
    width:Dimensions.get('window').width,
    height:310,
    backgroundColor:"#fff"
  },
  searchTouch:{
    height:44,
    backgroundColor:"#fff",
    flexDirection:"row",
    paddingLeft:25,
    paddingRight:25,
    borderTopWidth:1,
    borderTopColor:"#eaeaea",
    elevation: 2,
    shadowColor: "#050001",
    shadowOffset: { height: 1, width: 1 },
    shadowOpacity: .1,
    shadowRadius: 2,
    marginTop:2,
    alignItems:"center"
  },
  searchBtn:{
    width:150,
    height:25,
    alignItems:"center",
    justifyContent:"center",
    borderRadius:3,
  },
  backColor1:{
    backgroundColor:"#eee",
    marginRight:20,
  },
  backColor2:{
    backgroundColor:"#3a8ff3"
  },
  timeIput:{
    height:13,
    width:80,
    alignItems:"center",
    justifyContent:"center",
    borderWidth:1,
    borderColor:"#eaeaea"
  },
  mainView:{
    backgroundColor:"#f7f8fa"
  },
  listView:{
    backgroundColor:"#fff",
    marginBottom:10,
    shadowColor: "#050001",
    shadowOffset: { height: 1, width: 1 },
    shadowOpacity: .1,
    shadowRadius: 2,
    elevation: 1,
  },
  dsh:{
    color:"#00c482"
  },
  ddf:{
    color:"#feb358"
  },
  dyx:{
    color:"#4da0ff"
  },
  dqy:{
    color:"#2bc1e6"
  },
  djy:{
    color:"#e5c056"
  },
  wj:{
    color:"#7275ff"
  },
  faild:{
    color:"#f44d20"
  },
  noCustomView:{
    marginTop:55,
    paddingLeft:80,
    paddingRight:80,
    alignItems:"center",
  },
  noCustom:{
    marginBottom:15,
  },
  mt20:{
    marginBottom:15,
    marginTop:15,
  }









});
