import {StyleSheet,Dimensions} from 'react-native';
export const styles = StyleSheet.create({
  main:{
    flex:1,
    backgroundColor:'#f7f8fa',
  },
  scrollView:{
    marginBottom:50,
  },
  view:{
    marginBottom:10,
  },
  viewLine:{
    height:10,
  },
  title:{
    flexDirection:"row",
    paddingLeft:15,
    paddingRight:15,
    backgroundColor:"#fff",
    alignItems:"center",
    height:45
  },
  titleText:{
    marginLeft:5,
    fontWeight:"bold"
  },
  borderView:{
    borderColor:"#eaeaea",
    borderBottomWidth:1
  },
  mt10:{
    marginTop:10,
  },
  titleBtn:{
    height:26,
    borderWidth:1,
    borderColor:'#3a8ff3',
    justifyContent:"center",
    alignItems:'center',
    borderRadius:3,
    paddingLeft:5,
    paddingRight:5,
  },
  listView:{
    height:44,
    flexDirection:"row",
    borderBottomWidth:1,
    borderBottomColor:'#eaeaea',
    paddingLeft:15,
    paddingRight:15,
    backgroundColor:'#fff',
    justifyContent:"center",
    alignItems:'center',
  },
  listInput:{
    flex:1,
  },
  tooltip:{
    paddingLeft:15,
    paddingRight:15,
    paddingTop:10,
    paddingBottom:10,
  },
  row:{
    flexDirection:"row",
  },
  selectIcon:{
    marginLeft:5,
    marginTop:5,
  },
  viewBtn:{
    flexDirection:"row",
    position:'absolute',
    bottom:10,
    paddingLeft:15,
    paddingRight:15,
  },
  listBtn2:{
    flex:1,
    justifyContent:"center",
    alignItems:'center',
    borderRadius: 6,
    height:40,
    backgroundColor:'#3a8ff3',
    marginLeft:15,
  },
  listNoBtn2:{
    flex:1,
    justifyContent:"center",
    alignItems:'center',
    borderRadius: 6,
    height:40,
    borderWidth:1,
    borderColor:'#898989',
  },
  addImg:{
    flexDirection:"row",
    paddingLeft:15,
    paddingRight:15,
  },
  addImgImg:{
    marginLeft:15,
    marginRight:15,
    width:150,
    height:100,
    justifyContent:"center",
    alignItems:'center',
    backgroundColor:'#fff',
    borderWidth:1,
    borderColor:'#eaeaea',
  },
  remarks:{
    paddingLeft:15,
    paddingRight:15,
  },
  remarksInput:{
    height:140,
    marginTop:10,
    backgroundColor:'#fff',
    borderRadius:3,
    paddingLeft:5,
    paddingRight:5,
    paddingTop:5,
    paddingBottom:5,
    textAlignVertical:"top",
  },
  addImgTouch:{
    backgroundColor:"#fff",
    alignItems:"center",
    justifyContent:"center",
    width:150,
    height:120
  },
  radioView:{
    flex:1,
  },
  nav:{
    height:64,
    paddingTop:20,
    backgroundColor:'transparent',
    marginLeft:15,
    marginRight:15,
    flexDirection:"row",
    justifyContent:"center",
    alignItems:'center',
  },
  navCenter:{
    flex:1,
    justifyContent:"center",
    alignItems:'center',
  },
  navRight:{
    borderWidth:1,
    borderColor:'#ed6c5f',
    justifyContent:"center",
    alignItems:'center',
    width:56,
    height:26,
    borderRadius:3,
  },
});
