import {StyleSheet,Dimensions} from 'react-native';
export const styles = StyleSheet.create({
  container:{
    flex:1,
    backgroundColor:"#f7f8fa",
  },
  mainView:{
    backgroundColor:"#010101",
    flex:1,
    alignItems:"center",
    justifyContent:"center"
  },
  nav:{
    height:64,
    paddingTop:20,
    backgroundColor:'#141414',
    paddingLeft:15,
    paddingRight:15,
    flexDirection:"row",
    justifyContent:"center",
    alignItems:'center',
  },
  navCenter:{
    flex:1,
    justifyContent:"center",
    alignItems:'center',
  },
  navRight:{
    borderWidth:1,
    borderColor:'#ed6c5f',
    justifyContent:"center",
    alignItems:'center',
    width:56,
    height:26,
    borderRadius:3,
  },
  swiper:{
    height:(Dimensions.get('window').width/3)*2+50,
    width:Dimensions.get('window').width,
  },
  slideImg:{
    width:Dimensions.get('window').width,
    height:240,
    alignItems:"flex-end",
    justifyContent:"flex-end",
    paddingRight:15,
  },
  uploadView:{
    alignItems:"flex-end",
    justifyContent:"flex-end",
    marginRight:15,
    marginTop:15,
    width:Dimensions.get('window').width,
  },
  uploadTouch:{
    width:100,
    height:35,
    alignItems:"center",
    justifyContent:"center",
    backgroundColor:"#3a8ff3",
    borderRadius:3,
  },
  bottomView:{
    backgroundColor:"#141414",
    height:50,
    width:Dimensions.get('window').width,
    position:"absolute",
    left:0,
    bottom:0,
    alignItems:"center",
    flexDirection:"row",
    paddingLeft:15,
    zIndex:10
  },
  bottomTouch:{
    width:70,
    alignItems:"center",
    height:25,
    justifyContent:"center",
    borderRadius:3,
    borderColor:"#3a8ff3",
    borderWidth:1,
    marginRight:20,
  },
  paginationStyle:{
    position:'absolute',
    right:0,
    bottom:0,
    backgroundColor:'transparent',
    alignItems:"center",
    justifyContent:"center",
    height:32,
    width:Dimensions.get('window').width
  },
  bottomTouch1:{
    width:70,
    alignItems:"center",
    height:25,
    justifyContent:"center",
    borderRadius:3,
    borderColor:"#3a8ff3",
    borderWidth:1,
    marginRight:20,
    backgroundColor:"#3a8ff3"
  }
});
