import {StyleSheet,Dimensions} from 'react-native';
export const styles = StyleSheet.create({
  mainView:{
    flex:1,
  },
  titleView:{
    paddingLeft:15,
    paddingRight:15,
    height:44,
    backgroundColor:'#fff',
  },
  titleViewText:{
    lineHeight:44,
  },
  imgView:{
    width:Dimensions.get('window').width,
    paddingLeft:15,
    paddingRight:15,
    backgroundColor:'#fff',
    borderTopWidth:1,
    borderBottomWidth:1,
    borderColor:'#eaeaea',
    paddingTop:5,
  },
  img:{
    width:Dimensions.get('window').width-30,
    height:200,
    resizeMode:'cover'
  },
  imgViewText:{
    lineHeight:20,
    marginTop:10,
    marginBottom:20,
  },
  authorTime:{
    flexDirection:"row",
    paddingLeft:15,
    paddingRight:15,
    paddingBottom:10,
    paddingTop:10,
    backgroundColor:'#fff',
  },
  viewFlex:{
    flex:1,
  },
  listView:{
    paddingLeft:15,
    paddingRight:15,
    paddingBottom:100,
    paddingTop:10,
    backgroundColor:'#fff',
  },
  listText:{
    flexDirection:"row",
  },
  input:{
    flexDirection:"row",
    width:Dimensions.get('window').width-30,
    marginLeft:15,
    marginRight:15,
    marginTop:5,
    backgroundColor:'#fff',
    height:30,
    borderRadius:10,
  },
  inputImg:{
    marginTop:5,
    marginLeft:5,
    marginRight:10,
  },
  applyBtn:{
    width:60,
    height:60,
    position:'absolute',
    bottom:70,
    right:15,
    borderRadius:30,
    justifyContent:"center",
    alignItems:'center',
    paddingLeft:10,
    paddingRight:10,
    backgroundColor:'rgba(58,143,243,0.7)',
  },
  applyBtnText:{
    textAlign:'center',
    lineHeight:20,
  },
  lineHeight30:{
    lineHeight:30,
  },
  marginLeft5:{
    marginLeft:5,
  },
  marginLeft10:{
    marginLeft:10,
  },
});
