import {StyleSheet,Dimensions} from 'react-native';
export const styles = StyleSheet.create({
  container:{
    flex:1,
    backgroundColor:'#f7f8fa',
  },
  bgImg:{
    width:Dimensions.get('window').width,
    height:220
  },
  swiper:{
    height:220,
  },
  navBack:{
    height:44,
    width:60,
    justifyContent:"center",
    alignItems:'flex-start',
    position:'absolute',
    left:0,
    top:20,
    zIndex:0,
    paddingLeft:15,
  },
  viewNav:{
    backgroundColor:'#fff',
    flexDirection:"row",
    paddingLeft:15,
    paddingRight:15,
    marginTop:10,
    height:90,
  },
  navBtnA:{
    flex:1,
    justifyContent:"center",
    alignItems:'center',
  },
  navBtn:{
    justifyContent:"center",
    alignItems:'center',
  },
  navBtnImg:{
    marginBottom:5,
  },
  ViewList:{
    backgroundColor:'#fff',
    marginTop:10,
  },
  ViewTitle:{
    flexDirection:"row",
    marginLeft:15,
    marginRight:15,
    marginTop:10,
    marginBottom:10,
    borderLeftWidth:2,
    borderLeftColor:'#2a5ee0',
  },
  ViewTitleText:{
    flex:1,
    marginLeft:5,
  },
  ViewList1:{
    flexDirection:"row",
    position:'relative',
    paddingTop:10,
    paddingBottom:10,
    paddingLeft:15,
    paddingRight:15,
    marginBottom:10,
    borderBottomColor:'#eaeaea',
    borderBottomWidth:1,
  },
  ViewList1Img:{
    width:150,
    height:100,
    marginRight:5,
  },
  ViewList1Text:{
    flex:1,
  },
  authorTime:{
    flexDirection:"row",
    position:'absolute',
    bottom:0,
  },
  widthText:{
    width:50,
    overflow:"hidden",
    height:18
  },
  authorTimeText:{
    flex:1,
    marginLeft:5,
  },
  ViewList2:{
    flexDirection:"row",
    position:'relative',
    paddingTop:10,
    paddingBottom:10,
    paddingLeft:15,
    paddingRight:15,
    marginBottom:10,
    borderBottomColor:'#eaeaea',
    borderBottomWidth:1,
  },
  authorTime2:{
    flexDirection:"row",
    marginTop:10,
  },
  authorTime2Text:{
    flex:1,
    marginLeft:5,
  },
  titleText:{
    lineHeight:20,
  },
  proImgRest:{
    position:'absolute',
    left:15,
    top:10,
  }
});
