import {StyleSheet,Dimensions} from 'react-native';
export const styles = StyleSheet.create({
  container:{
    flex:1,
    backgroundColor:'#f7f8fa',
  },
  mainList:{
    flex:14,
    backgroundColor:'#f7f8fa',
    borderTopWidth:1,
    borderTopColor:'#eaeaea',
  },
  tabView:{
    backgroundColor:"#fff",
    borderTopWidth:0,
    borderBottomWidth:1,
    borderBottomColor:'#eaeaea',
  },
  tabBar:{
    height:40,
  },
  main:{
    marginTop:0,
    flex:1
  },
  mianView:{
    flex:1,
    backgroundColor:"#fff",
  },
  top:{
    marginTop:6,
    marginBottom:6,
    flexDirection:"row",
    paddingLeft:15,
    paddingRight:15,
  },
  topText:{
    flex:1,
  },
  list:{
    position:'relative',
    backgroundColor:"#fff",
    borderColor:"#ececec",
    borderBottomWidth:1
  },
  proImgRest:{
    position:"absolute",
    left:15,
    top:0,
  },
  listTitle:{
    marginTop:10,
    paddingLeft:15,
    paddingRight:15,
  },
  authorTime:{
    flexDirection:"row",
    marginTop:20,
    marginBottom:10,
    paddingLeft:15,
    paddingRight:15,
  },
  flex:{
    flex:1,
    marginLeft:5,
  },
  img:{
    position:'absolute',
    left:15,
    top:0,
  },
  mouthViewRest:{
    borderRadius:10,
    marginLeft:10,
    height:25,
    paddingLeft:15,
    paddingRight:15,
    justifyContent:"center",
  },
  mouthView:{
    borderRadius:10,
    marginLeft:10,
    height:25,
    paddingLeft:15,
    paddingRight:15,
    justifyContent:"center"
  },
  scrollView:{
    backgroundColor:"#fff",
    flex:1,
    paddingTop:10,
    marginBottom:10,
    marginTop:0,
    borderBottomWidth:1,
    borderColor:"#ececec"
  },
  tabsContainerStyle:{
    backgroundColor:"#fff",
    height:40,
    width:Dimensions.get('window').width,
  },
  tabStyle:{
    borderWidth:0,
    borderRadius:0,
    backgroundColor:"#fff",
    alignItems:"center",
    justifyContent:"center"
  },
  tabTextStyle:{

  },
  activeTabStyle:{
    backgroundColor:"#fff",
    borderRadius:0,
  },
  activeTabTextStyle:{
    color:"#3a8ff3"
  },
  signTitleView:{
    flexDirection:"row",
    backgroundColor:"#f9f9f9",
    height:65,
    alignItems:"center",
    justifyContent:"center",
    borderColor:"#eaeaea",
    borderBottomWidth:1,
    paddingTop:15,
    position:"relative"
  },
  backView:{
    width:60,
    height:44,
    alignItems:"flex-start",
    justifyContent:"center",
    position:"absolute",
    left:0,
    top:20,
    zIndex:10,
    paddingLeft:15,
  },
  searchView:{
    width:60,
    height:44,
    alignItems:"flex-end",
    justifyContent:"center",
    position:"absolute",
    right:0,
    top:20,
    zIndex:10,
    paddingRight:15
  },
});
