import {StyleSheet,Dimensions} from 'react-native';
export const styles = StyleSheet.create({
  mainList:{
    flex:1,
    backgroundColor:'#fff',
    borderTopWidth:1,
    borderTopColor:'#eaeaea',
    position:'relative',
  },
  container:{
    flex:1,
    backgroundColor:'#f7f8fa',
  },
  ScrollView:{
    marginBottom:0,
  },
  tabView:{
    backgroundColor:"#fff",
    position:"absolute",
    top:-1,
    left:0,
    borderTopWidth:0,
    borderBottomWidth:1,
    borderBottomColor:'#eaeaea',
  },
  tabBar:{
    height:40,
  },
  main:{
    marginTop:50,
    flex:1,
  },
  listView:{
    height:45,
    flexDirection:"row",
    borderBottomWidth:1,
    borderBottomColor:'#eaeaea',
    paddingLeft:15,
    paddingRight:15,
    backgroundColor:'#fff',
    alignItems:'center',
  },
  listViewText:{
    textAlign:"left"
  },
  bordershadow:{
    elevation: 2,
    shadowColor: "#000000",
    shadowOffset: { height: 1, width: 1 },
    shadowOpacity: .1,
    shadowRadius: 2,
  },
  listInput:{
    flex:1,
  },
  listInputRest:{
    height:127,
    marginTop:10,
    backgroundColor:'#fff',
    borderRadius:3,
    paddingLeft:5,
    paddingRight:5,
    paddingTop:5,
    paddingBottom:5,
    textAlignVertical:"top",
  },
  text:{
    marginLeft:15,
    marginRight:15,
    marginBottom:10,
  },
  btn:{
    position:'absolute',
    bottom:0,
  },
  listBtn:{
    width:Dimensions.get('window').width-30,
    marginLeft:15,
    marginRight:15,
    justifyContent:"center",
    alignItems:'center',
    borderRadius: 6,
    height:40,
    backgroundColor:'#3a8ff3',
  },
  listBtnRest:{
    marginTop:50,
  },
  listNoBtn:{
    width:Dimensions.get('window').width-30,
    marginLeft:15,
    marginRight:15,
    justifyContent:"center",
    alignItems:'center',
    borderRadius: 6,
    height:40,
    borderWidth:1,
    borderColor:'#898989',
    marginTop:10,
  },
  listViewRest:{
    marginTop:10,
    height:140,
    backgroundColor:"#fff",
    borderWidth:0
  },
  listViewTextRest:{
    alignSelf:"flex-start",
    paddingTop:7,
  },
  moreInput:{
    borderWidth:0,
    height:140,
    textAlignVertical:'top',
  },
  radioView:{
    flex:1,
  },
  viewBtn:{
    flexDirection:"row",
    position:'absolute',
    bottom:20,
    paddingLeft:15,
    paddingRight:15,
  },
  listBtn2:{
    flex:1,
    justifyContent:"center",
    alignItems:'center',
    borderRadius: 6,
    height:40,
    backgroundColor:'#3a8ff3',
    marginLeft:15,
  },
  listNoBtn2:{
    flex:1,
    justifyContent:"center",
    alignItems:'center',
    borderRadius: 6,
    height:40,
    borderWidth:1,
    borderColor:'#898989',
  },
  borderView:{
    borderColor:"#eaeaea",
    borderTopWidth:1
  },
  customBtn:{
    flexDirection:"row",
    position:'absolute',
    bottom:0,
    left:0
  },
  customBtnTou:{
    flex:1,
    justifyContent:"center",
    alignItems:'center',
    height:44,
    backgroundColor:'#3a8ff3',
  },
  enterView:{
    flexDirection:"row",
    paddingLeft:15,
    paddingRight:15,
    backgroundColor:"#fff",
    alignItems:"center",
    height:45,
  },
  enterTitle:{
    marginLeft:5,
    fontWeight:"bold"
  },
  enterBtn:{
    flexDirection:"row",
    alignItems:"center",
    justifyContent:"flex-end",
    height:45
  },
  mt10:{
    marginTop:10,
  },
  bzView:{
    marginBottom:0,
  },
  endView:{
    marginLeft:15,
    marginRight:15,
    paddingTop:25,
  },
  endView1:{

  },
  newlistViewRest:{
    alignItems:"center",
    justifyContent:"center"
  },
  pzImg:{
    width:150,
    height:100,
  },
  newlistView:{
    height:69,
    backgroundColor:"#fff",
    borderRadius:3,
    borderColor:"#eaeaea",
    borderBottomWidth:1,
    paddingLeft:15
  },
  inputPadding:{
    paddingTop:10,
    paddingBottom:10,
    paddingLeft:7,
    paddingRight:7,
    textAlignVertical:'top',
  },
  imgMl:{
    marginLeft:7
  },
  checkView:{
    flex:1,
    flexDirection:"row"
  },
  checkBoxView:{
    width:100
  },
  signTitleView:{
    flexDirection:"row",
    backgroundColor:"#f9f9f9",
    height:65,
    alignItems:"center",
    justifyContent:"center",
    borderColor:"#eaeaea",
    borderBottomWidth:1,
    paddingTop:15,
  },
  backView:{
    width:60,
    height:60,
    alignItems:"center",
    justifyContent:"center",
    position:"absolute",
    left:0,
    top:0,
    zIndex:10,
    paddingTop:15,
  },
  searchView:{
    width:60,
    height:60,
    alignItems:"center",
    justifyContent:"center",
    position:"absolute",
    right:0,
    top:0,
    zIndex:10,
    paddingTop:15,
  },
  reportState:{
    alignItems:"center",
    justifyContent:"center",
    paddingTop:10,
    paddingBottom:10,
  },
  reportView:{
    flexDirection:"row",
    alignItems:"center",
    justifyContent:"center",
    paddingBottom:5,
  },
  flexView:{
    flex:1,
    textAlign:"center"
  },
  flexRowView:{
    flexDirection:"row",
  },
  radioView1:{
    alignItems:"flex-start",
    justifyContent:"flex-start",
    backgroundColor:"#fff",
  },
  radioViewBtn:{
    borderColor:"#eaeaea",
    borderBottomWidth:1,
    paddingTop:10,
    paddingBottom:10,
    paddingLeft:15,
    paddingRight:15,
    backgroundColor:"#fff",
    width:Dimensions.get('window').width
  },
  flexLabel:{
    flex:1,
  },
  flexLabel1:{
    flex:2.8,
    height:40,
    justifyContent:"center",
  },
  drowViewBtn:{
    flexDirection:"row",
    backgroundColor:"#fff",
    height:45,
    alignItems:"center",
    justifyContent:"center",
    paddingLeft:15,
    paddingRight:15,
    borderColor:"#eaeaea",
    borderBottomWidth:1,
  },
  textInputValue:{
    height:40,
    borderWidth:0,
    alignItems:"center"
  },
  error:{
    paddingLeft:15,
    paddingTop:15,
    paddingBottom:15,
  },
  creatView:{
    paddingTop:50,
    alignItems:"center",
    justifyContent:"center",
    paddingLeft:15,
    paddingRight:15,
  },
  paddingBottom25:{
    paddingBottom:25
  },
  lineHeight20:{
    lineHeight:20
  },
  chooseType:{
    paddingTop:10,
    paddingBottom:10,
  },
  marginTop20:{
    marginTop:20,
  },
  inputRest:{
    marginLeft:20,
  },
  tabView:{
    alignItems:"center",
    backgroundColor:"#fff",
    width:Dimensions.get('window').width,
    borderColor:"#eaeaea",
    borderBottomWidth:1,
  },
  tabsContainerStyle:{
    backgroundColor:"#fff",
    height:40,
    width:Dimensions.get('window').width,
  },
  tabStyle:{
    borderWidth:0,
    borderRadius:0,
  },
  activeTabStyle:{
    backgroundColor:"#fff",
    borderRadius:0,
  },
  activeTabTextStyle:{
    color:"#3a8ff3"
  },
  viewBtnB:{
    marginTop:20,
    marginBottom:20,
  },
  nav:{
    height:64,
    paddingTop:20,
    backgroundColor:'transparent',
    marginLeft:15,
    marginRight:15,
    flexDirection:"row",
    justifyContent:"center",
    alignItems:'center',
  },
  navCenter:{
    flex:1,
    justifyContent:"center",
    alignItems:'center',
  },
  navRight:{
    borderWidth:1,
    borderColor:'#ed6c5f',
    justifyContent:"center",
    alignItems:'center',
    width:56,
    height:26,
    borderRadius:3,
  },
  bzViewM:{
    backgroundColor:"#f7f8fa",
  },
  bzViewMTitle:{
    padding:15,
  },
  newlistViewM:{
    height:200,
    backgroundColor:"#fff",
    marginLeft:15,
    marginRight:15,
    width:Dimensions.get('window').width-30,
    borderRadius:6,
    borderColor:"#eaeaea",
    borderWidth:1,
    padding:10
  },
  inputM:{
    flex:1,
    textAlignVertical:'top',
  },
  viewBtnM:{
    flexDirection:"row",
    paddingLeft:15,
    paddingRight:15,
    marginTop:20,
  },
  enterBtnM:{
    flexDirection:"row",
    alignItems:"center",
    justifyContent:"flex-end",
    height:45,
    paddingRight:15,
  },
  scrollViewM:{
    marginBottom:45,
  },
  title:{
    height:44,
    flexDirection:"row",
    paddingLeft:15,
    paddingRight:15,
    backgroundColor:'#fff',
    justifyContent:"center",
    alignItems:'center',
  },
  title1:{
    height:44,
    flexDirection:"row",
    paddingLeft:15,
    paddingRight:15,
    justifyContent:"center",
    alignItems:'center',
  },
  titleText:{
    flex:1,
  },
  remarks:{
    paddingLeft:15,
    paddingRight:15,
    paddingTop:15,
    paddingBottom:15,
    backgroundColor:"#fff",
    flex:1,
    marginBottom:70,
  },
  remarks1:{
    flexDirection:"row",
    backgroundColor:"#fff",
    elevation: 1,
    shadowColor: "#000000",
    shadowOffset: { height: 1, width: 1 },
    shadowOpacity: .1,
    shadowRadius: 1,
    alignItems:"center",
    paddingLeft:15,
    paddingRight:15,
    paddingTop:10,
    paddingBottom:10,
  },
  remarksInput:{
    height:140,
    marginTop:10,
    backgroundColor:'#fff',
    borderRadius:6,
    paddingLeft:10,
    paddingRight:10,
    paddingTop:10,
    paddingBottom:10,
    textAlignVertical:"top",
    borderWidth:1,
    borderColor:"#eaeaea"
  },
  remarksInput1:{
    alignItems:"center",
    includeFontPadding:false,
    padding:0,
    flex:1
  },
  bd10:{
    marginTop:10
  },
  listView1:{
    height:35,
    flexDirection:"row",
    paddingLeft:15,
    paddingRight:15,
    backgroundColor:'#fff',
    alignItems:'center',
  },
  bw:{
    borderBottomWidth:1,
    borderBottomColor:"#eaeaea"
  },
  viewBtn1:{
    flexDirection:"row",
    paddingLeft:15,
    paddingRight:15,
    marginTop:30,
  }
});
