import {StyleSheet,Dimensions} from 'react-native';
export const styles = StyleSheet.create({
  container:{
    flex:1,
    backgroundColor:'#f7f8fa',
  },
  mianView:{
    flex:1,
    backgroundColor:"#fff",
  },
  offlineView:{
    flexDirection:"row",
    paddingLeft:15,
    paddingRight:15,
    paddingTop:10,
    paddingBottom:5,
    borderBottomWidth:1,
    borderColor:"#eaeaea",
    position:"relative"
  },
  offlineViewImg:{
    width:150,
    height:100,
  },
  offlineRight:{
    flex:1,
    paddingLeft:15,
    position:"relative",
    paddingRight:15
  },
  rightBottom:{
    flexDirection:"row",
    alignItems:"center"
  },
  bottomText:{
    flex:1,
    lineHeight:20,
  },
  allianceTextRest:{
    paddingTop:10,
    paddingBottom:10,
    paddingLeft:15,
  },
  tabView:{
    alignItems:"center",
    backgroundColor:"#f9f9f9",
    width:Dimensions.get('window').width,
    borderColor:"#eaeaea",
    borderBottomWidth:1,
    position:"relative"
  },
  tabsContainerStyle:{
    backgroundColor:"#f9f9f9",
    height:60,
    width:200,
    paddingTop:20
  },
  tabStyle:{
    borderWidth:0,
    borderRadius:0,
    backgroundColor:"#f9f9f9",
  },
  tabTextStyle:{

  },
  activeTabStyle:{
    backgroundColor:"#f9f9f9",
    borderBottomWidth:2,
    borderColor:"#3a8ff3",
    borderRadius:0,
  },
  activeTabTextStyle:{
    color:"#3a8ff3"
  },
  backView:{
    width:60,
    height:44,
    justifyContent:"center",
    position:"absolute",
    left:0,
    top:20,
    zIndex:10,
    paddingLeft:15,
  },
  bottomTxt:{
    paddingBottom:5,
  },
  bottomBtn:{
    width:60,
    height:25,
    alignItems:"center",
    justifyContent:"center",
    borderColor:"#3a8ff3",
    borderWidth:1,
    borderRadius:3
  },
  bottomBtnText:{
    color:"#3a8ff3"
  },
  bottomTitle:{
    flex:1
  },
  EditView:{
    width:60,
    height:44,
    alignItems:"flex-end",
    justifyContent:"center",
    position:"absolute",
    right:0,
    top:20,
    zIndex:10,
    paddingRight:15
  },
  ForumListTitle:{
    flexDirection:"row",
    paddingLeft:15,
    paddingRight:15,
    alignItems:"center",
    borderBottomWidth:1,
    borderColor:"#ececec"
  },
  allianceText:{
    flex:1,
    paddingTop:8,
    paddingBottom:8,
  },
  proImg:{
    position:"absolute",
    left:15,
    right:0,
  },
  ForumText:{
    marginTop:10,
    flex:1,
  },
  bottomTop:{
    paddingBottom:12,
    marginTop:30,
  },
  flexView:{
    flex:3.5,
    flexDirection:"row",
  },
  flexTitle:{
    marginRight:20,
  },
  offlineRightRest:{
    borderColor:"#eaeaea",
    borderBottomWidth:1,
  },
  proImgRest:{
    position:"absolute",
    left:15,
    top:10,
  },








});
