import {StyleSheet,Dimensions} from 'react-native';
export const styles = StyleSheet.create({
  container:{
    flex:1,
    backgroundColor:'#fff',
  },
  titleView:{
    paddingLeft:15,
    paddingRight:15,
    height:44,
  },
  titleViewText:{
    lineHeight:44,
  },
  img:{
    width:Dimensions.get('window').width,
    height:260,
    resizeMode:'cover'
  },
  imgViewText:{
    paddingLeft:15,
    paddingRight:15,
    height:28,
    lineHeight:28,
  },
  authorTime:{
    flexDirection:"row",
    paddingLeft:15,
    paddingRight:15,
    paddingBottom:15,
    paddingTop:20,
  },
  viewFlex:{
    flex:1,
  },
  message:{
    height:26,
    paddingLeft:15,
  },
  messageText:{
    lineHeight:26,
  },
  marginLeft5:{
    marginLeft:5,
  },
  marginLeft10:{
    marginLeft:10,
  },
  ViewList:{
    flexDirection:"row",
    paddingLeft:15,
    paddingRight:15,
    paddingTop:10,
    paddingBottom:20,
  },
  ViewListText:{
    flex:1,
  },
  headImg:{
    width:40,
    height:40,
    marginRight:10,
  },
  inputView:{
    backgroundColor:'#f7f8fa',
    paddingTop:10,
    paddingBottom:10,
  },
  input:{
    flexDirection:"row",
    width:Dimensions.get('window').width-30,
    marginLeft:15,
    marginRight:15,
    height:30,
    borderRadius:10,
    backgroundColor:'#fff',
  },
  inputImg:{
    marginTop:5,
    marginLeft:5,
    marginRight:10,
  },
  lineHeight20:{
    lineHeight:20,
  },
});
