import {StyleSheet,Dimensions} from 'react-native';
export const styles = StyleSheet.create({
  main:{
    flex:1,
    backgroundColor:"#f7f8fa",
  },
  rankBg:{
    width:Dimensions.get('window').width,
  },
  rankView:{
    flexDirection:"row",
    alignItems:'center',
    justifyContent:"center",
    position:"relative"
  },
  touchBack:{
    position:"absolute",
    left:0,
    top:20,
    width:60,
    height:44,
    backgroundColor:"transparent",
    justifyContent:"center",
    paddingLeft:15,
    zIndex:10,
  },
  rankTitle:{
    backgroundColor:"transparent",
    paddingTop:28,
  },
  container:{
    flex:1,
  },
  rankList:{
    flexDirection:"row",
    backgroundColor:"#fff",
    marginBottom:10,
    paddingLeft:25,
    paddingRight:15,
    paddingTop:5,
    paddingBottom:10,
  },
  rankTop:{
    position:"relative",
  },
  rankTopImg:{
    width:44,
    height:44,
    borderRadius:22,
  },
  porImg:{
    position:"absolute",
    left:0,
    top:37,
  },
  rankMiddle:{
    flex:1,
    marginLeft:20,
  },
  rankText:{
    marginBottom:10,
  },
  rankTxt:{
    marginTop:5,
    marginBottom:7,
    lineHeight:20
  },
  webView:{
    flex:1,
    borderWidth:0,
    borderColor:'transparent',
    backgroundColor:'#fff',
    height:60,
  }
});
