import {StyleSheet,Dimensions} from 'react-native';

export const styles = StyleSheet.create({
  formGroupStyle:{

  },
  textboxViewStyle:{
    height:44,
    flexDirection:"row",
    borderBottomWidth:1,
    borderBottomColor:'#eaeaea',
    paddingLeft:15,
    paddingRight:15,
    backgroundColor:'#fff',
    justifyContent:"center",
    alignItems:'center'
  },
  selectViewStyle:{
    flexDirection:"row",
    backgroundColor:"#fff",
    marginTop:10,
    height:40,
    alignItems:"center",
    justifyContent:"center",
    paddingLeft:15,
    paddingRight:15,
    borderColor:"#eaeaea",
    borderTopWidth:1,
    borderBottomWidth:1
  },
  controlLabelStyle:{

  },
  selectControlLabelStyle:{
    flex:1,
  },
  selectStyle:{
    flex:1,
  },
  selectTextInputValueStyle:{
    padding:10,
    borderWidth:0,
  },
  requireLableStyle:{

  },
  helpBlockStyle:{
    paddingLeft:15,
    paddingRight:15,
    paddingTop:10,
    paddingBottom:10
  },
  errorBlockStyle:{
    paddingLeft:15,
    paddingTop:15,
    paddingBottom:15
  },
  textboxStyle:{
    flex:1
  },
  viewHeightStyle:{
    height:10
  },
  titleViewStyle:{
    height:44,
    justifyContent:"center",
    alignItems:'center',
    flexDirection:"row",
    paddingLeft:15,
    paddingRight:15,
    backgroundColor:'#fff',
    borderBottomWidth:1,
    borderBottomColor:'#eaeaea',
  },
  titleTextStyle:{
    flex:1,
  },
  mulTextboxViewStyle:{
    paddingLeft:15,
    paddingRight:15,
    paddingTop:10,
  },
  mulTextboxStyle:{
    height:140,
    marginTop:10,
    backgroundColor:'#fff',
    borderRadius:3,
    paddingLeft:5,
    paddingRight:5,
    paddingTop:5,
    paddingBottom:5,
    borderWidth:1,
    borderColor:'#eaeaea'
  }
});
