import {StyleSheet,Dimensions} from 'react-native';
export const styles = StyleSheet.create({
  main:{
    flex:1,
    backgroundColor:'#fff',
  },
  nav:{
    height:64,
    paddingTop:20,
    position:'relative',
    backgroundColor:'#f9f9f9',
  },
  navIconLeft:{
    width:60,
    height:44,
    justifyContent:"center",
    alignItems:'flex-start',
    position:'absolute',
    top:20,
    left:0,
    zIndex:0,
    paddingLeft:15,
  },
  navIconRight:{
    width:60,
    height:44,
    justifyContent:"center",
    alignItems:'flex-end',
    position:'absolute',
    top:20,
    right:0,
    paddingRight:15,
  },
  detailsTitle:{
    width:Dimensions.get('window').width,
    paddingLeft:15,
    paddingRight:15,
    paddingTop:8,
    paddingBottom:8,
    justifyContent:"center",
    alignItems:'center',
    backgroundColor:'#fff',
  },
  titleText:{
    textAlign:'center',
  },
  DetailsView:{
   flex:1,
   backgroundColor:"#fff"
  },
  img:{
    width:Dimensions.get('window').width-30,
    height:260,
    resizeMode:'cover',
  },
  numDate:{
    paddingTop:8,
    paddingBottom:16,
    flexDirection:"row",
    paddingLeft:15,
    paddingRight:15,
  },
  textCenter:{
    flex:1,
    marginLeft:5,
  },
  authorTime:{
    flexDirection:"row",
    paddingLeft:15,
    paddingRight:15,
    paddingBottom:15,
    paddingTop:20,
    justifyContent:"center",
    alignItems:'center',
  },
  viewFlex:{
    flex:1,
    paddingTop:0,
    paddingBottom:0,
  },
  message:{
    height:26,
    paddingLeft:15,
  },
  messageText:{
    lineHeight:26,
  },
  marginLeft5:{
    marginLeft:5,
  },
  marginLeft10:{
    marginLeft:10,
  },
  ViewList:{
    flexDirection:"row",
    paddingLeft:15,
    paddingRight:15,
    paddingTop:10,
    paddingBottom:20,
  },
  ViewListText:{
    flex:1,
  },
  headImg:{
    width:40,
    height:40,
    marginRight:10,
  },
  inputView:{
    backgroundColor:'#f7f8fa',
    paddingTop:10,
    paddingBottom:10,
    width:Dimensions.get('window').width,
  },
  input:{
    flexDirection:"row",
    width:Dimensions.get('window').width-30,
    marginLeft:15,
    marginRight:15,
    height:30,
    borderRadius:10,
    backgroundColor:'#fff',
  },
  inputImg:{
    marginTop:5,
    marginLeft:5,
    marginRight:10,
  },
  lineHeight20:{
    lineHeight:20,
  },
  applyBtn:{
    width:60,
    height:60,
    position:'absolute',
    bottom:70,
    right:15,
    borderRadius:30,
    justifyContent:"center",
    alignItems:'center',
    paddingLeft:10,
    paddingRight:10,
    backgroundColor:'rgba(58,143,243,0.7)',
  },
  applyBtnText:{
    textAlign:'center',
    lineHeight:20,
  },
  webView:{
    flex:1,
    borderWidth:0,
    borderColor:'transparent',
    backgroundColor:'#fff',
  },
  mask:{
    flex:1,
    backgroundColor:'rgba(0,0,0,0.7)',
    justifyContent:"flex-end"
  },
  closeBtn:{
    height:40,
    backgroundColor:'#fff',
    width:Dimensions.get('window').width,
    marginTop:10,
    justifyContent:"center",
    alignItems:'center',
  },
  share:{
    flexDirection:"row",
    paddingTop:10,
    paddingBottom:10,
    backgroundColor:'#fff',
  },
  shareView:{
    flex:1,
    justifyContent:"center",
    alignItems:'center',
  },
  shareText:{
    marginTop:15,
  },
});
