import {StyleSheet,Dimensions} from 'react-native';
export const styles = StyleSheet.create({
  mainList:{
    flex:1,
    backgroundColor:'#fff',
    borderTopWidth:1,
    borderTopColor:'#eaeaea',
  },
  bgColor:{
    backgroundColor:"#f7f8fa"
  },
  nav:{
    flexDirection:"row",
    height:64,
    paddingTop:20,
    backgroundColor:'#f9f9f9',
    justifyContent:"center",
    alignItems:'center',
  },
  navTitle:{
    height:44,
    flex:1,
    justifyContent:"center",
    alignItems:'center',
  },
  backIcon:{
    width:60,
    height:44,
    justifyContent:"center",
    alignItems:'flex-start',
    paddingLeft:15,
  },
  navLeft:{
    width:60,
    height:44,
    justifyContent:"center",
    alignItems:'flex-end',
    paddingRight:15,
  },
  listView:{
    height:44,
    flexDirection:"row",
    borderBottomWidth:1,
    borderBottomColor:'#eaeaea',
    paddingLeft:15,
    paddingRight:15,
    backgroundColor:'#fff',
  },
  lineBoder:{
    height:44,
    flexDirection:"row",
    borderBottomWidth:1,
    borderTopWidth:1,
    borderTopColor:'#eaeaea',
    borderBottomColor:'#eaeaea',
    paddingLeft:15,
    paddingRight:15,
    backgroundColor:'#fff',
    alignItems:"center",
    justifyContent:"center"
  },
  listTitle:{
    fontWeight:"bold",
    flex:1
  },
  rightDel:{
    alignItems:"flex-end",
    justifyContent:"center",
    width:80,
    height:44,
  },
  listViewRest:{
    height:110,
    flexDirection:"row",
    borderBottomWidth:0,
    paddingLeft:15,
    paddingRight:15,
    backgroundColor:'#fff',
    alignItems:"flex-start"
  },
  listViewLeft:{
    justifyContent:"center",
    alignItems:'center',
  },
  listViewLeft1:{
    justifyContent:"center",
    alignItems:'center',
    borderTopWidth:1,
    borderTopColor:"#eaeaea",
  },
  borderTop:{
    borderTopWidth:1,
    borderTopColor:'#eaeaea',
  },
  borderBottom:{
    borderBottomWidth:1,
    borderBottomColor:'#eaeaea',
  },
  listInput:{
    flex:5,
    justifyContent:"center",
    alignItems:'flex-start',
  },
  listLeft:{
    flex:1.5,
    paddingTop:0,
    paddingTop:12,
  },
  listInputView:{
    flex:5,
    justifyContent:"center",
    alignItems:'flex-start',
  },
  textAlignRight:{
    textAlign:'right',
    flex:3,
    color:'#898989',
  },
  moreInput:{
    height:100,
    paddingTop:10,
    paddingBottom:10,
    textAlignVertical:'top',
  },
  listHeight110:{
    height:110,
  },
  verificationView:{
    paddingLeft:5,
    paddingRight:5,
    height:24,
    borderWidth:1,
    borderColor:'#3a8ff3',
    justifyContent:"center",
    alignItems:'center',
    borderRadius:4,
    marginTop:10,
  },
  verificationText:{
    color:'#3a8ff3',
  },
  listBtn:{
    width:Dimensions.get('window').width-30,
    marginLeft:15,
    marginRight:15,
    justifyContent:"center",
    alignItems:'center',
    borderRadius: 6,
    height:40,
    backgroundColor:'#3a8ff3',
  },
  listNoBtn:{
    width:Dimensions.get('window').width-30,
    marginLeft:15,
    marginRight:15,
    justifyContent:"center",
    alignItems:'center',
    borderRadius: 6,
    height:40,
    backgroundColor:'#ccc',
  },
  viewBtn:{
    flexDirection:"row",
    position:'absolute',
    bottom:20,
    paddingLeft:15,
    paddingRight:15,
  },
  listBtn2:{
    flex:1,
    justifyContent:"center",
    alignItems:'center',
    borderRadius: 6,
    height:40,
    backgroundColor:'#3a8ff3',
    marginLeft:15,
  },
  listNoBtn2:{
    flex:1,
    justifyContent:"center",
    alignItems:'center',
    borderRadius: 6,
    height:40,
    borderWidth:1,
    borderColor:'#898989',
  },
  listViewText:{
    justifyContent:"center",
    alignItems:'flex-start',
    flex:2,
  },
  listViewTextRest:{
    paddingTop:10
  },
  listText:{
    marginLeft:15,
    marginRight:15,
    marginTop:15,
    alignItems:"center",
  },
  listTextRow:{
    flexDirection:"row",
    paddingTop:10,
    paddingLeft:15
  },
  bgRest:{
    backgroundColor:"#fff",
    paddingTop:0,
  },
  flex1:{
    flex:1,
    marginLeft:20,
  },
  flex2:{
    marginTop:50,
  },
  listRightText:{
    textAlign:'right',
  },
  listLeftText:{
    textAlign:'left',
  },
  listCenterText:{
    textAlign:'center',
  },
  listAddImg:{
    marginLeft:80,
    marginRight:80,
    marginTop:15,
  },
  imgText:{
    marginTop:10,
  },
  headImg:{
    width:24,
    height:24,
    borderRadius:12,
  },
  listImgCenter:{
    alignItems:"center",
  },
  listIcon:{
    color:'#3a8ff3',
    marginTop:10,
  },
  viewText:{
    width:Dimensions.get('window').width-60,
    marginLeft:30,
    marginRight:30,
  },
  city:{
    marginLeft:15,
    marginRight:15,
    marginTop:15,
    marginBottom:20,
  },
  marginTop180:{
    marginTop:180,
  },
  marginTop50:{
    marginTop:50,
  },
  marginTop10:{
    marginTop:10,
  },
  marginLeft15:{
    marginLeft:15,
  },
  marginBottom10:{
    marginBottom:10,
  },
  positionBottom70:{
    marginTop:50,
  },
  positionBottom20:{
    marginTop:20,
    marginBottom:10,
  },
  mainView:{
    backgroundColor:"#f7f8fa",
    flex:1
  },
  selectIcon:{
    marginTop:18,
  },
  radioView:{
    alignItems:"center",
    justifyContent:"center",
  },
  radioBtn:{
    width:(Dimensions.get('window').width)/2,
    paddingLeft:50,
    paddingTop:10,
    paddingBottom:10,
  },
  checkBoxView:{
    marginRight:10,
  },
  positionR:{
    position:'relative',
  },
  positionA:{
    position:'absolute',
    right:15,
  },

  cityNav:{
    backgroundColor:"#f9f9f9",
    height:60,
    flexDirection:"row",
    paddingLeft:12,
    paddingTop:20,
    alignItems:"center",
    borderColor:"#eaeaea",
    borderBottomWidth:1
  },
  cityNavText:{
    textAlign:"center",
    flex:1,
  },
  hotCityTitle:{
    paddingLeft:12,
    paddingBottom:15,
    paddingTop:15,
  },
  hotCityList:{
    flexDirection:"row",
    flexWrap:"wrap",
  },
  hotCityTouch:{
    backgroundColor:"#fff",
    paddingTop:10,
    paddingBottom:10,
    alignItems:"center",
    borderRadius:3,
    marginLeft:10,
    marginRight:8,
    marginBottom:8,
    justifyContent:"center",
    width:(Dimensions.get('window').width-75)/4,
    borderColor:"#eaeaea",
    borderWidth:1
  },
  hotCityTouchRest:{
    backgroundColor:"#3a8ff3",
    paddingTop:10,
    paddingBottom:10,
    alignItems:"center",
    borderRadius:3,
    marginLeft:12,
    marginRight:13,
    marginBottom:10,
    justifyContent:"center",
    width:(Dimensions.get('window').width-75)/4,
    borderColor:"#3a8ff3",
    borderWidth:1
  },
  hotCityText:{
    textAlign:"center",
  },
  Fullscreen:{
    flex:1,
    backgroundColor:"#fff"
  },
  textMiTxt:{
    textAlign:'center',
    marginTop:145,
  },
  settingBtn:{
    alignItems:"center",
    justifyContent:"center",
    height:44,
    borderTopWidth:1,
    borderBottomWidth:1,
    borderColor:'#eaeaea',
    paddingLeft:15,
    paddingRight:15,
    backgroundColor:'#fff',
    marginTop:10,
  },
  bindcompany:{
    flex:5,
    justifyContent:"center",
    alignItems:'flex-start',
  },
  bindcompanyText:{
    justifyContent:"center",
    alignItems:'flex-start',
    flex:2.3,
  },
  listViewText1:{
    justifyContent:"center",
    alignItems:'flex-start',
    flex:3,
  },
  cardView:{
    flex:2.2,
  },
  addBrander:{
    flexDirection:"row",
    alignItems:"center",
    justifyContent:"center",
    marginTop:10,
  },
  leftM:{
    marginLeft:10,
  },
  modalBody:{
    backgroundColor:"rgba(0,0,0,0.7)",
    flex:1,
    alignItems:"flex-end",
    justifyContent:"flex-end"
  },
  btnView:{
    height:45,
    flexDirection:"row",
    backgroundColor:"#fff",
    borderTopWidth:1,
    borderTopColor:"#ececec"
  },
  btnViewTouch:{
    flex:1,
    alignItems:"center",
    justifyContent:"center"
  },
  leftTouch:{
   alignItems:"flex-start",
   paddingLeft:15,
  },
  rightTouch:{
   alignItems:"flex-end",
   paddingRight:15
  },
  bodyText:{
    color:"#5e99dd"
  },
  modalContent:{
    backgroundColor:"#fff",
    height:265,
    width:Dimensions.get('window').width,
    flexDirection:"row",
    borderTopWidth:1,
    borderTopColor:"#ececec"
  },
  leftView:{
    flex:2,
    borderRightColor:"#ececec",
    borderRightWidth:1,
  },
  recommendMain:{
    backgroundColor:"#fff"
  },
  recommendMainRest:{
    backgroundColor:"#f7f8fa"
  },
  liView:{
    alignItems:"center",
    justifyContent:"center",
    height:45,
    borderBottomWidth:1,
    borderBottomColor:"#ececec"
  },
  liViewRest:{
    alignItems:"center",
    justifyContent:"center",
    height:45,
    borderBottomWidth:1,
    borderBottomColor:"#ececec",
    backgroundColor:"#f7f8fa"
  },
  rightView:{
    flex:4,
  },
  checkNode:{
    flexDirection:"row",
    flex:1,
    alignItems:'center',
    flexDirection:"row",
    marginRight:10,
  },
  listInputRest:{
    flex:5,
    justifyContent:"flex-start",
    alignItems:'center',
    flexDirection:"row",
    position:"relative"
  },
  addNode:{
    position:"absolute",
    top:10,
    right:0,
  },
  rightText:{
    marginRight:5,
  },
  tipsText:{
    color:"#ccc"
  },
  ViewtipsText:{
    alignItems:"center",
    marginTop:10
  }
});
