import {StyleSheet,Dimensions} from 'react-native';
export const nav = StyleSheet.create({
  navDefault:{
    width:Dimensions.get('window').width,
    height:64,
    backgroundColor:'#f9f9f9',
    flexDirection:"row",
    paddingTop:20,
    borderBottomWidth:1,
    borderBottomColor:"#eaeaea"
  },
  navDark:{
    width:Dimensions.get('window').width,
    height:64,
    backgroundColor:'#1e222a',
    flexDirection:"row",
    paddingTop:20,
  },
  navTran:{
    width:Dimensions.get('window').width,
    height:64,
    backgroundColor:'transparent',
    flexDirection:"row",
    paddingTop:20,
  },
  navLeft:{
    width:60,
    height:44,
    backgroundColor:'transparent',
    justifyContent:"center",
    alignItems:'flex-start',
    paddingLeft:15,
  },
  navCenter:{
    width:Dimensions.get('window').width-120,
    height:44,
    backgroundColor:'transparent',
    justifyContent:"center",
    alignItems:'center',
  },
  navRight:{
    width:60,
    height:44,
    backgroundColor:'transparent',
    justifyContent:"center",
    alignItems:'flex-end',
    paddingRight:15,
  },
});
