import {StyleSheet,Dimensions} from 'react-native';
export const styles = StyleSheet.create({
  loginView:{
    flex: 1,
  },
  loginViewNav:{
    flexDirection:"row",
    height:44,
    marginLeft:15,
    marginRight:15,
  },
  loginViewNavL:{
    flex:1,
    justifyContent:'center',
  },
  loginViewNavC:{
    backgroundColor:'transparent',
    justifyContent:'center',
  },
  loginViewNavR:{
    flex:1,
    justifyContent:'center',
  },
  loginViewNavLText:{
    textAlign:'left',
  },
  loginViewNavCText:{
    textAlign:'center',
  },
  loginViewNavRText:{
    textAlign:'right',
  },
  loginImage:{
    width:Dimensions.get('window').width,
    paddingTop:20,
    height:Dimensions.get('window').height,
  },
  loginViewInput:{
    marginLeft:30,
    marginRight:30,
    height:44,
    borderBottomColor:'rgba(234,234,234,0.7)',
    borderBottomWidth:1,
  },
  city:{
    marginLeft:30,
    marginRight:30,
    marginTop:15,
    marginBottom:20,
  },
  loginTextInput:{
    flex:1,
    justifyContent:"center",
  },
  loginMarginTop120:{
    marginTop:120,
  },
  loginMarginTop15:{
    marginTop:15,
  },
  loginBtn:{
    width:Dimensions.get('window').width-60,
    marginLeft:30,
    marginRight:30,
    justifyContent:"center",
    alignItems:'center',
    borderRadius: 6,
    height:40,
    backgroundColor:'#3a8ff3',
  },
  loginText:{
    flexDirection:"row",
    marginTop:10,
    marginLeft:30,
    marginRight:30,
  },
  loginTextTab:{
      flex:1,
  },
  loginText1:{
    color:'#3a8ff3',
  },
  loginText2:{
    textAlign:'right',
    color:'#3a8ff3',
  },

  cityNav:{
    backgroundColor:"#f9f9f9",
    height:60,
    flexDirection:"row",
    paddingLeft:12,
    paddingTop:20,
    alignItems:"center",
    borderColor:"#eaeaea",
    borderBottomWidth:1
  },
  cityNavText:{
    textAlign:"center",
    flex:1,
  },
  hotCityTitle:{
    paddingLeft:12,
    paddingBottom:15,
    paddingTop:15,
  },
  hotCityList:{
    flexDirection:"row",
    flexWrap:"wrap",
  },
  hotCityTouch:{
    backgroundColor:"#fff",
    paddingTop:10,
    paddingBottom:10,
    alignItems:"center",
    borderRadius:3,
    marginLeft:10,
    marginRight:8,
    marginBottom:8,
    justifyContent:"center",
    width:(Dimensions.get('window').width-75)/4,
    borderColor:"#eaeaea",
    borderWidth:1
  },
  hotCityTouchRest:{
    backgroundColor:"#3a8ff3",
    paddingTop:10,
    paddingBottom:10,
    alignItems:"center",
    borderRadius:3,
    marginLeft:12,
    marginRight:13,
    marginBottom:10,
    justifyContent:"center",
    width:(Dimensions.get('window').width-75)/4,
    borderColor:"#3a8ff3",
    borderWidth:1
  },
  hotCityText:{
    textAlign:"center",
  },
  Fullscreen:{
    flex:1,
    backgroundColor:"#fff"
  }
});
